//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZombustersWindows.Localization {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
#if WINDOWS
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ZombustersWindows.Localization.Strings", typeof(Strings).Assembly);
#elif NETCOREAPP
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("ZombustersMac.Localization.Strings", typeof(Strings).Assembly);
#endif
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string BackString {
            get {
                return ResourceManager.GetString("BackString", resourceCulture);
            }
        }
        
        internal static string ConfigurationString {
            get {
                return ResourceManager.GetString("ConfigurationString", resourceCulture);
            }
        }
        
        internal static string ConfirmEndSession {
            get {
                return ResourceManager.GetString("ConfirmEndSession", resourceCulture);
            }
        }
        
        internal static string ConfirmExitSample {
            get {
                return ResourceManager.GetString("ConfirmExitSample", resourceCulture);
            }
        }
        
        internal static string ConfirmForceStartGame {
            get {
                return ResourceManager.GetString("ConfirmForceStartGame", resourceCulture);
            }
        }
        
        internal static string ConfirmLeaveSession {
            get {
                return ResourceManager.GetString("ConfirmLeaveSession", resourceCulture);
            }
        }
        
        internal static string ConfirmMarketplace {
            get {
                return ResourceManager.GetString("ConfirmMarketplace", resourceCulture);
            }
        }
        
        internal static string ConfirmQuitGame {
            get {
                return ResourceManager.GetString("ConfirmQuitGame", resourceCulture);
            }
        }
        
        internal static string ConnectControllerToJoinString {
            get {
                return ResourceManager.GetString("ConnectControllerToJoinString", resourceCulture);
            }
        }
        
        internal static string CopyRightString {
            get {
                return ResourceManager.GetString("CopyRightString", resourceCulture);
            }
        }
        
        internal static string CreateSession {
            get {
                return ResourceManager.GetString("CreateSession", resourceCulture);
            }
        }
        
        internal static string EndSession {
            get {
                return ResourceManager.GetString("EndSession", resourceCulture);
            }
        }
        
        internal static string ErrorDisconnected {
            get {
                return ResourceManager.GetString("ErrorDisconnected", resourceCulture);
            }
        }
        
        internal static string ErrorGamerPrivilege {
            get {
                return ResourceManager.GetString("ErrorGamerPrivilege", resourceCulture);
            }
        }
        
        internal static string ErrorHostEndedSession {
            get {
                return ResourceManager.GetString("ErrorHostEndedSession", resourceCulture);
            }
        }
        
        internal static string ErrorNetwork {
            get {
                return ResourceManager.GetString("ErrorNetwork", resourceCulture);
            }
        }
        
        internal static string ErrorNetworkNotAvailable {
            get {
                return ResourceManager.GetString("ErrorNetworkNotAvailable", resourceCulture);
            }
        }
        
        internal static string ErrorRemovedByHost {
            get {
                return ResourceManager.GetString("ErrorRemovedByHost", resourceCulture);
            }
        }
        
        internal static string ErrorSessionFull {
            get {
                return ResourceManager.GetString("ErrorSessionFull", resourceCulture);
            }
        }
        
        internal static string ErrorSessionNotFound {
            get {
                return ResourceManager.GetString("ErrorSessionNotFound", resourceCulture);
            }
        }
        
        internal static string ErrorSessionNotJoinable {
            get {
                return ResourceManager.GetString("ErrorSessionNotJoinable", resourceCulture);
            }
        }
        
        internal static string ErrorTrialMode {
            get {
                return ResourceManager.GetString("ErrorTrialMode", resourceCulture);
            }
        }
        
        internal static string ErrorUnknown {
            get {
                return ResourceManager.GetString("ErrorUnknown", resourceCulture);
            }
        }
        
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        internal static string FindSessions {
            get {
                return ResourceManager.GetString("FindSessions", resourceCulture);
            }
        }
        
        internal static string FriendOpenGroupString {
            get {
                return ResourceManager.GetString("FriendOpenGroupString", resourceCulture);
            }
        }
        
        internal static string HostSuffix {
            get {
                return ResourceManager.GetString("HostSuffix", resourceCulture);
            }
        }
        
        internal static string JoinSession {
            get {
                return ResourceManager.GetString("JoinSession", resourceCulture);
            }
        }
        
        internal static string LeaveSession {
            get {
                return ResourceManager.GetString("LeaveSession", resourceCulture);
            }
        }
        
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        internal static string Lobby {
            get {
                return ResourceManager.GetString("Lobby", resourceCulture);
            }
        }
        
        internal static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        internal static string MainMenuLobbyString {
            get {
                return ResourceManager.GetString("MainMenuLobbyString", resourceCulture);
            }
        }
        
        internal static string MainMenuString {
            get {
                return ResourceManager.GetString("MainMenuString", resourceCulture);
            }
        }
        
        internal static string MatchmakingLobbyString {
            get {
                return ResourceManager.GetString("MatchmakingLobbyString", resourceCulture);
            }
        }
        
        internal static string MatchmakingMenuString {
            get {
                return ResourceManager.GetString("MatchmakingMenuString", resourceCulture);
            }
        }
        
        internal static string MatchmakingMMString {
            get {
                return ResourceManager.GetString("MatchmakingMMString", resourceCulture);
            }
        }
        
        internal static string MessageBoxUsage {
            get {
                return ResourceManager.GetString("MessageBoxUsage", resourceCulture);
            }
        }
        
        internal static string MessageGamerJoined {
            get {
                return ResourceManager.GetString("MessageGamerJoined", resourceCulture);
            }
        }
        
        internal static string MessageGamerLeft {
            get {
                return ResourceManager.GetString("MessageGamerLeft", resourceCulture);
            }
        }
        
        internal static string MyGroupString {
            get {
                return ResourceManager.GetString("MyGroupString", resourceCulture);
            }
        }
        
        internal static string NetworkBusy {
            get {
                return ResourceManager.GetString("NetworkBusy", resourceCulture);
            }
        }
        
        internal static string NoSessionsFound {
            get {
                return ResourceManager.GetString("NoSessionsFound", resourceCulture);
            }
        }
        
        internal static string P1PressStartString {
            get {
                return ResourceManager.GetString("P1PressStartString", resourceCulture);
            }
        }
        
        internal static string P2PressStartString {
            get {
                return ResourceManager.GetString("P2PressStartString", resourceCulture);
            }
        }
        
        internal static string P3PressStartString {
            get {
                return ResourceManager.GetString("P3PressStartString", resourceCulture);
            }
        }
        
        internal static string P4PressStartString {
            get {
                return ResourceManager.GetString("P4PressStartString", resourceCulture);
            }
        }
        
        internal static string Paused {
            get {
                return ResourceManager.GetString("Paused", resourceCulture);
            }
        }
        
        internal static string PlayerMatch {
            get {
                return ResourceManager.GetString("PlayerMatch", resourceCulture);
            }
        }
        
        internal static string PlayerSignInString {
            get {
                return ResourceManager.GetString("PlayerSignInString", resourceCulture);
            }
        }
        
        internal static string PressStartString {
            get {
                return ResourceManager.GetString("PressStartString", resourceCulture);
            }
        }
        
        internal static string QuitGame {
            get {
                return ResourceManager.GetString("QuitGame", resourceCulture);
            }
        }
        
        internal static string ResumeGame {
            get {
                return ResourceManager.GetString("ResumeGame", resourceCulture);
            }
        }
        
        internal static string ReturnToDashboardMMString {
            get {
                return ResourceManager.GetString("ReturnToDashboardMMString", resourceCulture);
            }
        }
        
        internal static string ReturnToDashboardString {
            get {
                return ResourceManager.GetString("ReturnToDashboardString", resourceCulture);
            }
        }
        
        internal static string ReturnToLobby {
            get {
                return ResourceManager.GetString("ReturnToLobby", resourceCulture);
            }
        }
        
        internal static string SelectString {
            get {
                return ResourceManager.GetString("SelectString", resourceCulture);
            }
        }
        
        internal static string SinglePlayer {
            get {
                return ResourceManager.GetString("SinglePlayer", resourceCulture);
            }
        }
        
        internal static string StartMatchmakingMenuString {
            get {
                return ResourceManager.GetString("StartMatchmakingMenuString", resourceCulture);
            }
        }
        
        internal static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        internal static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        internal static string String3 {
            get {
                return ResourceManager.GetString("String3", resourceCulture);
            }
        }
        
        internal static string String4 {
            get {
                return ResourceManager.GetString("String4", resourceCulture);
            }
        }
        
        internal static string String5 {
            get {
                return ResourceManager.GetString("String5", resourceCulture);
            }
        }
        
        internal static string String6 {
            get {
                return ResourceManager.GetString("String6", resourceCulture);
            }
        }
        
        internal static string String7 {
            get {
                return ResourceManager.GetString("String7", resourceCulture);
            }
        }
        
        internal static string String8 {
            get {
                return ResourceManager.GetString("String8", resourceCulture);
            }
        }
        
        internal static string String9 {
            get {
                return ResourceManager.GetString("String9", resourceCulture);
            }
        }
        
        internal static string SystemLink {
            get {
                return ResourceManager.GetString("SystemLink", resourceCulture);
            }
        }
        
        internal static string StartMatchmakingMMString {
            get {
                return ResourceManager.GetString("StartMatchmakingMMString", resourceCulture);
            }
        }
        
        internal static string PlaylistMatchmakingMMString {
            get {
                return ResourceManager.GetString("PlaylistMatchmakingMMString", resourceCulture);
            }
        }
        
        internal static string PlaylistMatchmakingString {
            get {
                return ResourceManager.GetString("PlaylistMatchmakingString", resourceCulture);
            }
        }
        
        internal static string NetworkMatchmakingMMString {
            get {
                return ResourceManager.GetString("NetworkMatchmakingMMString", resourceCulture);
            }
        }
        
        internal static string NetworkMatchmakingString {
            get {
                return ResourceManager.GetString("NetworkMatchmakingString", resourceCulture);
            }
        }
        
        internal static string LocalGameMMString {
            get {
                return ResourceManager.GetString("LocalGameMMString", resourceCulture);
            }
        }
        
        internal static string LocalGameString {
            get {
                return ResourceManager.GetString("LocalGameString", resourceCulture);
            }
        }
        
        internal static string CreateGameMenuString {
            get {
                return ResourceManager.GetString("CreateGameMenuString", resourceCulture);
            }
        }
        
        internal static string CreateGameMMString {
            get {
                return ResourceManager.GetString("CreateGameMMString", resourceCulture);
            }
        }
        
        internal static string CustomMatchMenuString {
            get {
                return ResourceManager.GetString("CustomMatchMenuString", resourceCulture);
            }
        }
        
        internal static string CustomMatchMMString {
            get {
                return ResourceManager.GetString("CustomMatchMMString", resourceCulture);
            }
        }
        
        internal static string QuickMatchMenuString {
            get {
                return ResourceManager.GetString("QuickMatchMenuString", resourceCulture);
            }
        }
        
        internal static string QuickMatchMMString {
            get {
                return ResourceManager.GetString("QuickMatchMMString", resourceCulture);
            }
        }
        
        internal static string FindSessionMenuString {
            get {
                return ResourceManager.GetString("FindSessionMenuString", resourceCulture);
            }
        }
        
        internal static string FindSessionMMString {
            get {
                return ResourceManager.GetString("FindSessionMMString", resourceCulture);
            }
        }
        
        internal static string LevelSelectMenuString {
            get {
                return ResourceManager.GetString("LevelSelectMenuString", resourceCulture);
            }
        }
        
        internal static string LevelSelectMMString {
            get {
                return ResourceManager.GetString("LevelSelectMMString", resourceCulture);
            }
        }
        
        internal static string MaxPlayersMenuString {
            get {
                return ResourceManager.GetString("MaxPlayersMenuString", resourceCulture);
            }
        }
        
        internal static string MaxPlayersMMString {
            get {
                return ResourceManager.GetString("MaxPlayersMMString", resourceCulture);
            }
        }
        
        internal static string PrivateSlotsMenuString {
            get {
                return ResourceManager.GetString("PrivateSlotsMenuString", resourceCulture);
            }
        }
        
        internal static string PrivateSlotsMMString {
            get {
                return ResourceManager.GetString("PrivateSlotsMMString", resourceCulture);
            }
        }
        
        internal static string LobbyMenuString {
            get {
                return ResourceManager.GetString("LobbyMenuString", resourceCulture);
            }
        }
        
        internal static string WaitingForPlayersMenuString {
            get {
                return ResourceManager.GetString("WaitingForPlayersMenuString", resourceCulture);
            }
        }
        
        internal static string InviteMenuString {
            get {
                return ResourceManager.GetString("InviteMenuString", resourceCulture);
            }
        }
        
        internal static string LeaveMenuString {
            get {
                return ResourceManager.GetString("LeaveMenuString", resourceCulture);
            }
        }
        
        internal static string PartyMenuString {
            get {
                return ResourceManager.GetString("PartyMenuString", resourceCulture);
            }
        }
        
        internal static string ShowGamerCardMenuString {
            get {
                return ResourceManager.GetString("ShowGamerCardMenuString", resourceCulture);
            }
        }
        
        internal static string ToggleReadyMenuString {
            get {
                return ResourceManager.GetString("ToggleReadyMenuString", resourceCulture);
            }
        }
        
        internal static string CancelString {
            get {
                return ResourceManager.GetString("CancelString", resourceCulture);
            }
        }
        
        internal static string ConfirmReturnMainMenuMMString {
            get {
                return ResourceManager.GetString("ConfirmReturnMainMenuMMString", resourceCulture);
            }
        }
        
        internal static string ConfirmReturnMainMenuString {
            get {
                return ResourceManager.GetString("ConfirmReturnMainMenuString", resourceCulture);
            }
        }
        
        internal static string AchievementsMenuString {
            get {
                return ResourceManager.GetString("AchievementsMenuString", resourceCulture);
            }
        }
        
        internal static string AchievementsMMString {
            get {
                return ResourceManager.GetString("AchievementsMMString", resourceCulture);
            }
        }
        
        internal static string CreditsMenuString {
            get {
                return ResourceManager.GetString("CreditsMenuString", resourceCulture);
            }
        }
        
        internal static string CreditsMMString {
            get {
                return ResourceManager.GetString("CreditsMMString", resourceCulture);
            }
        }
        
        internal static string ExtrasMenuString {
            get {
                return ResourceManager.GetString("ExtrasMenuString", resourceCulture);
            }
        }
        
        internal static string ExtrasMMString {
            get {
                return ResourceManager.GetString("ExtrasMMString", resourceCulture);
            }
        }
        
        internal static string StartGameMenuString {
            get {
                return ResourceManager.GetString("StartGameMenuString", resourceCulture);
            }
        }
        
        internal static string GameOverString {
            get {
                return ResourceManager.GetString("GameOverString", resourceCulture);
            }
        }
        
        internal static string CharacterSelectString {
            get {
                return ResourceManager.GetString("CharacterSelectString", resourceCulture);
            }
        }
        
        internal static string AutosaveStartMenuString {
            get {
                return ResourceManager.GetString("AutosaveStartMenuString", resourceCulture);
            }
        }
        
        internal static string AutosaveTitleMenuString {
            get {
                return ResourceManager.GetString("AutosaveTitleMenuString", resourceCulture);
            }
        }
        
        internal static string MusicVolumeString {
            get {
                return ResourceManager.GetString("MusicVolumeString", resourceCulture);
            }
        }
        
        internal static string SaveAndExitString {
            get {
                return ResourceManager.GetString("SaveAndExitString", resourceCulture);
            }
        }
        
        internal static string SoundEffectVolumeString {
            get {
                return ResourceManager.GetString("SoundEffectVolumeString", resourceCulture);
            }
        }
        
        internal static string BackWithoutSavingString {
            get {
                return ResourceManager.GetString("BackWithoutSavingString", resourceCulture);
            }
        }
        
        internal static string ChangeCharacterMenuString {
            get {
                return ResourceManager.GetString("ChangeCharacterMenuString", resourceCulture);
            }
        }
        
        internal static string ChangeSoundVolumeMenuString {
            get {
                return ResourceManager.GetString("ChangeSoundVolumeMenuString", resourceCulture);
            }
        }
        
        internal static string SwitchReadyMenuString {
            get {
                return ResourceManager.GetString("SwitchReadyMenuString", resourceCulture);
            }
        }
        
        internal static string SettingsMenuString {
            get {
                return ResourceManager.GetString("SettingsMenuString", resourceCulture);
            }
        }
        
        internal static string HowToPlayInGameString {
            get {
                return ResourceManager.GetString("HowToPlayInGameString", resourceCulture);
            }
        }
        
        internal static string PlayerFourString {
            get {
                return ResourceManager.GetString("PlayerFourString", resourceCulture);
            }
        }
        
        internal static string PlayerOneString {
            get {
                return ResourceManager.GetString("PlayerOneString", resourceCulture);
            }
        }
        
        internal static string PlayerThreeString {
            get {
                return ResourceManager.GetString("PlayerThreeString", resourceCulture);
            }
        }
        
        internal static string PlayerTwoString {
            get {
                return ResourceManager.GetString("PlayerTwoString", resourceCulture);
            }
        }
        
        internal static string QuitToMainMenuInGameString {
            get {
                return ResourceManager.GetString("QuitToMainMenuInGameString", resourceCulture);
            }
        }
        
        internal static string RestartLevelInGameString {
            get {
                return ResourceManager.GetString("RestartLevelInGameString", resourceCulture);
            }
        }
        
        internal static string LevelSelectionString {
            get {
                return ResourceManager.GetString("LevelSelectionString", resourceCulture);
            }
        }
        
        internal static string ReadySelPlayerString {
            get {
                return ResourceManager.GetString("ReadySelPlayerString", resourceCulture);
            }
        }
        
        internal static string ClearedGameplayString {
            get {
                return ResourceManager.GetString("ClearedGameplayString", resourceCulture);
            }
        }
        
        internal static string PrepareNextWaveGameplayString {
            get {
                return ResourceManager.GetString("PrepareNextWaveGameplayString", resourceCulture);
            }
        }
        
        internal static string WaveGameplayString {
            get {
                return ResourceManager.GetString("WaveGameplayString", resourceCulture);
            }
        }
        
        internal static string LeaderboardMenuString {
            get {
                return ResourceManager.GetString("LeaderboardMenuString", resourceCulture);
            }
        }
        
        internal static string LeaderboardMMString {
            get {
                return ResourceManager.GetString("LeaderboardMMString", resourceCulture);
            }
        }
        
        internal static string HTPAimShootString {
            get {
                return ResourceManager.GetString("HTPAimShootString", resourceCulture);
            }
        }
        
        internal static string HTPChangeSongString {
            get {
                return ResourceManager.GetString("HTPChangeSongString", resourceCulture);
            }
        }
        
        internal static string HTPChangeWeaponString {
            get {
                return ResourceManager.GetString("HTPChangeWeaponString", resourceCulture);
            }
        }
        
        internal static string HTPGrenadeString {
            get {
                return ResourceManager.GetString("HTPGrenadeString", resourceCulture);
            }
        }
        
        internal static string HTPMoveString {
            get {
                return ResourceManager.GetString("HTPMoveString", resourceCulture);
            }
        }
        
        internal static string HTPReviveTeammateString {
            get {
                return ResourceManager.GetString("HTPReviveTeammateString", resourceCulture);
            }
        }
        
        internal static string HTPTauntString {
            get {
                return ResourceManager.GetString("HTPTauntString", resourceCulture);
            }
        }
        
        internal static string HTPExplanationString {
            get {
                return ResourceManager.GetString("HTPExplanationString", resourceCulture);
            }
        }
        
        internal static string HTPPauseString {
            get {
                return ResourceManager.GetString("HTPPauseString", resourceCulture);
            }
        }
        
        internal static string CongratssEndGameString {
            get {
                return ResourceManager.GetString("CongratssEndGameString", resourceCulture);
            }
        }
        
        internal static string CreditsThanksForPlayingString {
            get {
                return ResourceManager.GetString("CreditsThanksForPlayingString", resourceCulture);
            }
        }
        
        internal static string GPRestartCurrentWaveString {
            get {
                return ResourceManager.GetString("GPRestartCurrentWaveString", resourceCulture);
            }
        }
        
        internal static string GPRestartFromBeginningString {
            get {
                return ResourceManager.GetString("GPRestartFromBeginningString", resourceCulture);
            }
        }
        
        internal static string GPReturnLobbySupportString {
            get {
                return ResourceManager.GetString("GPReturnLobbySupportString", resourceCulture);
            }
        }
        
        internal static string GPReturnMMSupportString {
            get {
                return ResourceManager.GetString("GPReturnMMSupportString", resourceCulture);
            }
        }
        
        internal static string GPReturnToMainMenuString {
            get {
                return ResourceManager.GetString("GPReturnToMainMenuString", resourceCulture);
            }
        }
        
        internal static string TrialModeMenuString {
            get {
                return ResourceManager.GetString("TrialModeMenuString", resourceCulture);
            }
        }
        
        internal static string UnlockFullGameMenuString {
            get {
                return ResourceManager.GetString("UnlockFullGameMenuString", resourceCulture);
            }
        }
        
        internal static string YouSavedCityEndGameString {
            get {
                return ResourceManager.GetString("YouSavedCityEndGameString", resourceCulture);
            }
        }
        
        internal static string MatchmakingHostOwnGameString {
            get {
                return ResourceManager.GetString("MatchmakingHostOwnGameString", resourceCulture);
            }
        }
        
        internal static string HTPMenuSupportString {
            get {
                return ResourceManager.GetString("HTPMenuSupportString", resourceCulture);
            }
        }
        
        internal static string LeaderboardScoreString {
            get {
                return ResourceManager.GetString("LeaderboardScoreString", resourceCulture);
            }
        }
        
        internal static string NumberEight {
            get {
                return ResourceManager.GetString("NumberEight", resourceCulture);
            }
        }
        
        internal static string NumberFive {
            get {
                return ResourceManager.GetString("NumberFive", resourceCulture);
            }
        }
        
        internal static string NumberFour {
            get {
                return ResourceManager.GetString("NumberFour", resourceCulture);
            }
        }
        
        internal static string NumberNine {
            get {
                return ResourceManager.GetString("NumberNine", resourceCulture);
            }
        }
        
        internal static string NumberOne {
            get {
                return ResourceManager.GetString("NumberOne", resourceCulture);
            }
        }
        
        internal static string NumberSeven {
            get {
                return ResourceManager.GetString("NumberSeven", resourceCulture);
            }
        }
        
        internal static string NumberSix {
            get {
                return ResourceManager.GetString("NumberSix", resourceCulture);
            }
        }
        
        internal static string NumberTen {
            get {
                return ResourceManager.GetString("NumberTen", resourceCulture);
            }
        }
        
        internal static string NumberThree {
            get {
                return ResourceManager.GetString("NumberThree", resourceCulture);
            }
        }
        
        internal static string NumberTwo {
            get {
                return ResourceManager.GetString("NumberTwo", resourceCulture);
            }
        }
        
        internal static string ReconnectControllerString {
            get {
                return ResourceManager.GetString("ReconnectControllerString", resourceCulture);
            }
        }
        
        internal static string PCPressAnyKeyString {
            get {
                return ResourceManager.GetString("PCPressAnyKeyString", resourceCulture);
            }
        }
        
        internal static string VisitRetrowaxMenuStringWP {
            get {
                return ResourceManager.GetString("VisitRetrowaxMenuStringWP", resourceCulture);
            }
        }
        
        internal static string WPPlayNewGame {
            get {
                return ResourceManager.GetString("WPPlayNewGame", resourceCulture);
            }
        }
        
        internal static string WPPlayNewGameMMString {
            get {
                return ResourceManager.GetString("WPPlayNewGameMMString", resourceCulture);
            }
        }
        
        internal static string WPTapScreen {
            get {
                return ResourceManager.GetString("WPTapScreen", resourceCulture);
            }
        }
        
        internal static string WPShakeToChangeSong {
            get {
                return ResourceManager.GetString("WPShakeToChangeSong", resourceCulture);
            }
        }
        
        internal static string WPTip {
            get {
                return ResourceManager.GetString("WPTip", resourceCulture);
            }
        }
        
        internal static string FullScreenMenuString {
            get {
                return ResourceManager.GetString("FullScreenMenuString", resourceCulture);
            }
        }
        
        internal static string PCExplanationString {
            get {
                return ResourceManager.GetString("PCExplanationString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ADD ZOMBUSTERS TO MY WISHLIST.
        /// </summary>
        internal static string WishListGameMenu
        {
            get
            {
                return ResourceManager.GetString("WishListGameMenu", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to If you want to support us we would appreciate if you add Zombusters to your wishlist..
        /// </summary>
        internal static string WishListGameMenuHelp
        {
            get
            {
                return ResourceManager.GetString("WishListGameMenuHelp", resourceCulture);
            }
        }

        internal static string ReviewMenuString {
            get {
                return ResourceManager.GetString("ReviewMenuString", resourceCulture);
            }
        }
        
        internal static string ReviewMMString {
            get {
                return ResourceManager.GetString("ReviewMMString", resourceCulture);
            }
        }
        
        internal static string RateThisAppCancel {
            get {
                return ResourceManager.GetString("RateThisAppCancel", resourceCulture);
            }
        }
        
        internal static string RateThisAppOK {
            get {
                return ResourceManager.GetString("RateThisAppOK", resourceCulture);
            }
        }
        
        internal static string RateThisAppText {
            get {
                return ResourceManager.GetString("RateThisAppText", resourceCulture);
            }
        }
        
        internal static string RateThisAppTitle {
            get {
                return ResourceManager.GetString("RateThisAppTitle", resourceCulture);
            }
        }
        
        internal static string ChangeLanguageOption {
            get {
                return ResourceManager.GetString("ChangeLanguageOption", resourceCulture);
            }
        }

        internal static string DemoEndScreenLine1
        {
            get
            {
                return ResourceManager.GetString("DemoEndScreenLine1", resourceCulture);
            }
        }

        internal static string DemoEndScreenLine2
        {
            get
            {
                return ResourceManager.GetString("DemoEndScreenLine2", resourceCulture);
            }
        }

        internal static string DemoEndScreenLine3
        {
            get
            {
                return ResourceManager.GetString("DemoEndScreenLine3", resourceCulture);
            }
        }

        internal static string DemoEndScreenLine4
        {
            get
            {
                return ResourceManager.GetString("DemoEndScreenLine4", resourceCulture);
            }
        }
    }
}
