//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZombustersWindows.Localization {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
#if WINDOWS
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZombustersWindows.Localization.Strings", typeof(Strings).Assembly);
#elif NETCOREAPP
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZombustersMac.Localization.Strings", typeof(Strings).Assembly);
#endif
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CHALLENGES.
        /// </summary>
        internal static string AchievementsMenuString {
            get {
                return ResourceManager.GetString("AchievementsMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show challenges list..
        /// </summary>
        internal static string AchievementsMMString {
            get {
                return ResourceManager.GetString("AchievementsMMString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zombusters uses an Autosave feature wich will automatically 
        ///save your progress throughout the title. Autosave will 
        ///overwrite information without confirmation. Do not switch 
        ///off the power when the autosave indication is present..
        /// </summary>
        internal static string AutosaveStartMenuString {
            get {
                return ResourceManager.GetString("AutosaveStartMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AUTOSAVE.
        /// </summary>
        internal static string AutosaveTitleMenuString {
            get {
                return ResourceManager.GetString("AutosaveTitleMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back.
        /// </summary>
        internal static string BackString {
            get {
                return ResourceManager.GetString("BackString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exit Without Saving.
        /// </summary>
        internal static string BackWithoutSavingString {
            get {
                return ResourceManager.GetString("BackWithoutSavingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        internal static string CancelString {
            get {
                return ResourceManager.GetString("CancelString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change Character.
        /// </summary>
        internal static string ChangeCharacterMenuString {
            get {
                return ResourceManager.GetString("ChangeCharacterMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change Language.
        /// </summary>
        internal static string ChangeLanguageOption {
            get {
                return ResourceManager.GetString("ChangeLanguageOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Change Sound/Music Volume.
        /// </summary>
        internal static string ChangeSoundVolumeMenuString {
            get {
                return ResourceManager.GetString("ChangeSoundVolumeMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SELECT CHARACTER.
        /// </summary>
        internal static string CharacterSelectString {
            get {
                return ResourceManager.GetString("CharacterSelectString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CLEARED.
        /// </summary>
        internal static string ClearedGameplayString {
            get {
                return ResourceManager.GetString("ClearedGameplayString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings.
        /// </summary>
        internal static string ConfigurationString {
            get {
                return ResourceManager.GetString("ConfigurationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to end this session?.
        /// </summary>
        internal static string ConfirmEndSession {
            get {
                return ResourceManager.GetString("ConfirmEndSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to exit this sample?.
        /// </summary>
        internal static string ConfirmExitSample {
            get {
                return ResourceManager.GetString("ConfirmExitSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to start the game,.
        /// </summary>
        internal static string ConfirmForceStartGame {
            get {
                return ResourceManager.GetString("ConfirmForceStartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to leave this session?.
        /// </summary>
        internal static string ConfirmLeaveSession {
            get {
                return ResourceManager.GetString("ConfirmLeaveSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Online gameplay is not available in trial mode..
        /// </summary>
        internal static string ConfirmMarketplace {
            get {
                return ResourceManager.GetString("ConfirmMarketplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to quit this game?.
        /// </summary>
        internal static string ConfirmQuitGame {
            get {
                return ResourceManager.GetString("ConfirmQuitGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You will return to matchmaking menu.
        /// </summary>
        internal static string ConfirmReturnMainMenuMMString {
            get {
                return ResourceManager.GetString("ConfirmReturnMainMenuMMString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to exit?.
        /// </summary>
        internal static string ConfirmReturnMainMenuString {
            get {
                return ResourceManager.GetString("ConfirmReturnMainMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CONGRATULATIONS!.
        /// </summary>
        internal static string CongratssEndGameString {
            get {
                return ResourceManager.GetString("CongratssEndGameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Connect controller to play.
        /// </summary>
        internal static string ConnectControllerToJoinString {
            get {
                return ResourceManager.GetString("ConnectControllerToJoinString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a © RETROWAX GAMES. 2011-2020 ALL RIGHTS RESERVED.
        /// </summary>
        internal static string CopyRightString {
            get {
                return ResourceManager.GetString("CopyRightString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREATE GAME.
        /// </summary>
        internal static string CreateGameMenuString {
            get {
                return ResourceManager.GetString("CreateGameMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Host a game..
        /// </summary>
        internal static string CreateGameMMString {
            get {
                return ResourceManager.GetString("CreateGameMMString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create Session.
        /// </summary>
        internal static string CreateSession {
            get {
                return ResourceManager.GetString("CreateSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREDITS.
        /// </summary>
        internal static string CreditsMenuString {
            get {
                return ResourceManager.GetString("CreditsMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show creator credits..
        /// </summary>
        internal static string CreditsMMString {
            get {
                return ResourceManager.GetString("CreditsMMString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a THANKS FOR PLAYING!.
        /// </summary>
        internal static string CreditsThanksForPlayingString {
            get {
                return ResourceManager.GetString("CreditsThanksForPlayingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CUSTOM MATCH.
        /// </summary>
        internal static string CustomMatchMenuString {
            get {
                return ResourceManager.GetString("CustomMatchMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search for a game session to join within a set of 
        ///parameters..
        /// </summary>
        internal static string CustomMatchMMString {
            get {
                return ResourceManager.GetString("CustomMatchMMString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a We hope you have enjoyed the Demo.
        /// </summary>
        internal static string DemoEndScreenLine1 {
            get {
                return ResourceManager.GetString("DemoEndScreenLine1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prepare for more kind of enemies, more weapons, more power-ups and more surprises!.
        /// </summary>
        internal static string DemoEndScreenLine2 {
            get {
                return ResourceManager.GetString("DemoEndScreenLine2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Be sure to stop by the Steam page and add the game to your Wishlist.
        /// </summary>
        internal static string DemoEndScreenLine3 {
            get {
                return ResourceManager.GetString("DemoEndScreenLine3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Zombusters will be released fall 2020.
        /// </summary>
        internal static string DemoEndScreenLine4 {
            get {
                return ResourceManager.GetString("DemoEndScreenLine4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a End Session.
        /// </summary>
        internal static string EndSession {
            get {
                return ResourceManager.GetString("EndSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lost connection to the network session.
        /// </summary>
        internal static string ErrorDisconnected {
            get {
                return ResourceManager.GetString("ErrorDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must sign in a suitable gamer profile.
        /// </summary>
        internal static string ErrorGamerPrivilege {
            get {
                return ResourceManager.GetString("ErrorGamerPrivilege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Host ended the session.
        /// </summary>
        internal static string ErrorHostEndedSession {
            get {
                return ResourceManager.GetString("ErrorHostEndedSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a There was an error while.
        /// </summary>
        internal static string ErrorNetwork {
            get {
                return ResourceManager.GetString("ErrorNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Networking is turned.
        /// </summary>
        internal static string ErrorNetworkNotAvailable {
            get {
                return ResourceManager.GetString("ErrorNetworkNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Host kicked you out of the session.
        /// </summary>
        internal static string ErrorRemovedByHost {
            get {
                return ResourceManager.GetString("ErrorRemovedByHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This session is already full.
        /// </summary>
        internal static string ErrorSessionFull {
            get {
                return ResourceManager.GetString("ErrorSessionFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Session not found. It may have ended,.
        /// </summary>
        internal static string ErrorSessionNotFound {
            get {
                return ResourceManager.GetString("ErrorSessionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You must wait for the host to return to.
        /// </summary>
        internal static string ErrorSessionNotJoinable {
            get {
                return ResourceManager.GetString("ErrorSessionNotJoinable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This functionality is not available in trial mode.
        /// </summary>
        internal static string ErrorTrialMode {
            get {
                return ResourceManager.GetString("ErrorTrialMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a An unknown error occurred.
        /// </summary>
        internal static string ErrorUnknown {
            get {
                return ResourceManager.GetString("ErrorUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EXTRAS.
        /// </summary>
        internal static string ExtrasMenuString {
            get {
                return ResourceManager.GetString("ExtrasMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show the Extras menu. You can check how to play,
        ///Scoreboards or Credits..
        /// </summary>
        internal static string ExtrasMMString {
            get {
                return ResourceManager.GetString("ExtrasMMString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a FIND SESSION.
        /// </summary>
        internal static string FindSessionMenuString {
            get {
                return ResourceManager.GetString("FindSessionMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Find session to play..
        /// </summary>
        internal static string FindSessionMMString {
            get {
                return ResourceManager.GetString("FindSessionMMString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Find Sessions.
        /// </summary>
        internal static string FindSessions {
            get {
                return ResourceManager.GetString("FindSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a This party is open to friends..
        /// </summary>
        internal static string FriendOpenGroupString {
            get {
                return ResourceManager.GetString("FriendOpenGroupString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Toggle full screen mode.
        /// </summary>
        internal static string FullScreenMenuString {
            get {
                return ResourceManager.GetString("FullScreenMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GAME OVER.
        /// </summary>
        internal static string GameOverString {
            get {
                return ResourceManager.GetString("GameOverString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restart from current wave.
        /// </summary>
        internal static string GPRestartCurrentWaveString {
            get {
                return ResourceManager.GetString("GPRestartCurrentWaveString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restart from beginning.
        /// </summary>
        internal static string GPRestartFromBeginningString {
            get {
                return ResourceManager.GetString("GPRestartFromBeginningString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You are about to return to the party lobby. Any unsaved progress will be lost..
        /// </summary>
        internal static string GPReturnLobbySupportString {
            get {
                return ResourceManager.GetString("GPReturnLobbySupportString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You are about to return to the main menu. The session will disband, and any unsaved progress will be lost..
        /// </summary>
        internal static string GPReturnMMSupportString {
            get {
                return ResourceManager.GetString("GPReturnMMSupportString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Return to Main Menu.
        /// </summary>
        internal static string GPReturnToMainMenuString {
            get {
                return ResourceManager.GetString("GPReturnToMainMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  (host).
        /// </summary>
        internal static string HostSuffix {
            get {
                return ResourceManager.GetString("HostSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a HOW TO PLAY.
        /// </summary>
        internal static string HowToPlayInGameString {
            get {
                return ResourceManager.GetString("HowToPlayInGameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AIM + SHOOT.
        /// </summary>
        internal static string HTPAimShootString {
            get {
                return ResourceManager.GetString("HTPAimShootString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CHANGE SONG.
        /// </summary>
        internal static string HTPChangeSongString {
            get {
                return ResourceManager.GetString("HTPChangeSongString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CHANGE WEAPON.
        /// </summary>
        internal static string HTPChangeWeaponString {
            get {
                return ResourceManager.GetString("HTPChangeWeaponString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Use the Left Thumbstick to move your character.
        ///Use the Right Thumbsitck to fire at the Zombies.
        ///Shoot the enemies to accumulate points and to get
        ///PowerUps. Catch the PowerUps to gain a free life 
        ///or a new Weapon..
        /// </summary>
        internal static string HTPExplanationString {
            get {
                return ResourceManager.GetString("HTPExplanationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a GRENADE.
        /// </summary>
        internal static string HTPGrenadeString {
            get {
                return ResourceManager.GetString("HTPGrenadeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a How to play Zombusters..
        /// </summary>
        internal static string HTPMenuSupportString {
            get {
                return ResourceManager.GetString("HTPMenuSupportString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MOVE.
        /// </summary>
        internal static string HTPMoveString {
            get {
                return ResourceManager.GetString("HTPMoveString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PAUSE GAME.
        /// </summary>
        internal static string HTPPauseString {
            get {
                return ResourceManager.GetString("HTPPauseString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a REVIVE TEAMMATE.
        /// </summary>
        internal static string HTPReviveTeammateString {
            get {
                return ResourceManager.GetString("HTPReviveTeammateString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TAUNT.
        /// </summary>
        internal static string HTPTauntString {
            get {
                return ResourceManager.GetString("HTPTauntString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invite.
        /// </summary>
        internal static string InviteMenuString {
            get {
                return ResourceManager.GetString("InviteMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Join Session.
        /// </summary>
        internal static string JoinSession {
            get {
                return ResourceManager.GetString("JoinSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LEADERBOARDS.
        /// </summary>
        internal static string LeaderboardMenuString {
            get {
                return ResourceManager.GetString("LeaderboardMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Check out the score of your friends online or Local.
        /// </summary>
        internal static string LeaderboardMMString {
            get {
                return ResourceManager.GetString("LeaderboardMMString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SCORE.
        /// </summary>
        internal static string LeaderboardScoreString {
            get {
                return ResourceManager.GetString("LeaderboardScoreString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Leave.
        /// </summary>
        internal static string LeaveMenuString {
            get {
                return ResourceManager.GetString("LeaveMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Leave Session.
        /// </summary>
        internal static string LeaveSession {
            get {
                return ResourceManager.GetString("LeaveSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LEVEL SELECTION.
        /// </summary>
        internal static string LevelSelectionString {
            get {
                return ResourceManager.GetString("LevelSelectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LEVEL.
        /// </summary>
        internal static string LevelSelectMenuString {
            get {
                return ResourceManager.GetString("LevelSelectMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Choose the level to play..
        /// </summary>
        internal static string LevelSelectMMString {
            get {
                return ResourceManager.GetString("LevelSelectMMString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Loading....
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lobby.
        /// </summary>
        internal static string Lobby {
            get {
                return ResourceManager.GetString("Lobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LOBBY.
        /// </summary>
        internal static string LobbyMenuString {
            get {
                return ResourceManager.GetString("LobbyMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start a local game. You can play with three more
        ///players on the same console..
        /// </summary>
        internal static string LocalGameMMString {
            get {
                return ResourceManager.GetString("LocalGameMMString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LOCAL GAME.
        /// </summary>
        internal static string LocalGameString {
            get {
                return ResourceManager.GetString("LocalGameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Main Menu.
        /// </summary>
        internal static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a In Main Menu Lobby.
        /// </summary>
        internal static string MainMenuLobbyString {
            get {
                return ResourceManager.GetString("MainMenuLobbyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MAIN MENU.
        /// </summary>
        internal static string MainMenuString {
            get {
                return ResourceManager.GetString("MainMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Would you like to host a new game?.
        /// </summary>
        internal static string MatchmakingHostOwnGameString {
            get {
                return ResourceManager.GetString("MatchmakingHostOwnGameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a In Matchmaking Lobby.
        /// </summary>
        internal static string MatchmakingLobbyString {
            get {
                return ResourceManager.GetString("MatchmakingLobbyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MATCHMAKING.
        /// </summary>
        internal static string MatchmakingMenuString {
            get {
                return ResourceManager.GetString("MatchmakingMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Take your party to Xbox LIVE and into the frenetic 
        ///action of live combat. Up to four players co-operate 
        ///to survive wave after wave of the Zombie horde..
        /// </summary>
        internal static string MatchmakingMMString {
            get {
                return ResourceManager.GetString("MatchmakingMMString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MAX. PLAYERS.
        /// </summary>
        internal static string MaxPlayersMenuString {
            get {
                return ResourceManager.GetString("MaxPlayersMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a How many players would you like to play?.
        /// </summary>
        internal static string MaxPlayersMMString {
            get {
                return ResourceManager.GetString("MaxPlayersMMString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string MessageBoxUsage {
            get {
                return ResourceManager.GetString("MessageBoxUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} joined.
        /// </summary>
        internal static string MessageGamerJoined {
            get {
                return ResourceManager.GetString("MessageGamerJoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} left.
        /// </summary>
        internal static string MessageGamerLeft {
            get {
                return ResourceManager.GetString("MessageGamerLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Music Volume.
        /// </summary>
        internal static string MusicVolumeString {
            get {
                return ResourceManager.GetString("MusicVolumeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MY PARTY.
        /// </summary>
        internal static string MyGroupString {
            get {
                return ResourceManager.GetString("MyGroupString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Networking....
        /// </summary>
        internal static string NetworkBusy {
            get {
                return ResourceManager.GetString("NetworkBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Choose your Network for the Matchmaking. Play a 
        ///SystemLink or Xbox Live game..
        /// </summary>
        internal static string NetworkMatchmakingMMString {
            get {
                return ResourceManager.GetString("NetworkMatchmakingMMString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NETWORK.
        /// </summary>
        internal static string NetworkMatchmakingString {
            get {
                return ResourceManager.GetString("NetworkMatchmakingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No sessions found.
        /// </summary>
        internal static string NoSessionsFound {
            get {
                return ResourceManager.GetString("NoSessionsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eight.
        /// </summary>
        internal static string NumberEight {
            get {
                return ResourceManager.GetString("NumberEight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Five.
        /// </summary>
        internal static string NumberFive {
            get {
                return ResourceManager.GetString("NumberFive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Four.
        /// </summary>
        internal static string NumberFour {
            get {
                return ResourceManager.GetString("NumberFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nine.
        /// </summary>
        internal static string NumberNine {
            get {
                return ResourceManager.GetString("NumberNine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a One.
        /// </summary>
        internal static string NumberOne {
            get {
                return ResourceManager.GetString("NumberOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seven.
        /// </summary>
        internal static string NumberSeven {
            get {
                return ResourceManager.GetString("NumberSeven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Six.
        /// </summary>
        internal static string NumberSix {
            get {
                return ResourceManager.GetString("NumberSix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ten.
        /// </summary>
        internal static string NumberTen {
            get {
                return ResourceManager.GetString("NumberTen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Three.
        /// </summary>
        internal static string NumberThree {
            get {
                return ResourceManager.GetString("NumberThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Two.
        /// </summary>
        internal static string NumberTwo {
            get {
                return ResourceManager.GetString("NumberTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Player 1 Press Start.
        /// </summary>
        internal static string P1PressStartString {
            get {
                return ResourceManager.GetString("P1PressStartString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Player 2 Press Start.
        /// </summary>
        internal static string P2PressStartString {
            get {
                return ResourceManager.GetString("P2PressStartString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Player 3 Press Start.
        /// </summary>
        internal static string P3PressStartString {
            get {
                return ResourceManager.GetString("P3PressStartString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Player 4 Press Start.
        /// </summary>
        internal static string P4PressStartString {
            get {
                return ResourceManager.GetString("P4PressStartString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invite Party.
        /// </summary>
        internal static string PartyMenuString {
            get {
                return ResourceManager.GetString("PartyMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paused.
        /// </summary>
        internal static string Paused {
            get {
                return ResourceManager.GetString("Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Use A,S,D,W or Arrows to move your character.
        ///Use Left Mouse Button to fire at the Zombies.
        ///Shoot the enemies to accumulate points and to get
        ///PowerUps. Catch the PowerUps to gain a free life 
        ///or a new Weapon..
        /// </summary>
        internal static string PCExplanationString {
            get {
                return ResourceManager.GetString("PCExplanationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Press Any Key.
        /// </summary>
        internal static string PCPressAnyKeyString {
            get {
                return ResourceManager.GetString("PCPressAnyKeyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Player Four.
        /// </summary>
        internal static string PlayerFourString {
            get {
                return ResourceManager.GetString("PlayerFourString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a LIVE.
        /// </summary>
        internal static string PlayerMatch {
            get {
                return ResourceManager.GetString("PlayerMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Player One.
        /// </summary>
        internal static string PlayerOneString {
            get {
                return ResourceManager.GetString("PlayerOneString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Press GUIDE to Sign In.
        /// </summary>
        internal static string PlayerSignInString {
            get {
                return ResourceManager.GetString("PlayerSignInString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Player Three.
        /// </summary>
        internal static string PlayerThreeString {
            get {
                return ResourceManager.GetString("PlayerThreeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Player Two.
        /// </summary>
        internal static string PlayerTwoString {
            get {
                return ResourceManager.GetString("PlayerTwoString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Starts playlist for the selected Machmaking configuration..
        /// </summary>
        internal static string PlaylistMatchmakingMMString {
            get {
                return ResourceManager.GetString("PlaylistMatchmakingMMString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PLAYLIST.
        /// </summary>
        internal static string PlaylistMatchmakingString {
            get {
                return ResourceManager.GetString("PlaylistMatchmakingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Prepare for the next Wave.
        /// </summary>
        internal static string PrepareNextWaveGameplayString {
            get {
                return ResourceManager.GetString("PrepareNextWaveGameplayString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Press START button.
        /// </summary>
        internal static string PressStartString {
            get {
                return ResourceManager.GetString("PressStartString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PRIVATE SLOTS.
        /// </summary>
        internal static string PrivateSlotsMenuString {
            get {
                return ResourceManager.GetString("PrivateSlotsMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select number of private slots..
        /// </summary>
        internal static string PrivateSlotsMMString {
            get {
                return ResourceManager.GetString("PrivateSlotsMMString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a QUICK MATCH.
        /// </summary>
        internal static string QuickMatchMenuString {
            get {
                return ResourceManager.GetString("QuickMatchMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quickly join another player&apos;s game session..
        /// </summary>
        internal static string QuickMatchMMString {
            get {
                return ResourceManager.GetString("QuickMatchMMString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a QUIT GAME.
        /// </summary>
        internal static string QuitGame {
            get {
                return ResourceManager.GetString("QuitGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quit to Main Menu.
        /// </summary>
        internal static string QuitToMainMenuInGameString {
            get {
                return ResourceManager.GetString("QuitToMainMenuInGameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Later.
        /// </summary>
        internal static string RateThisAppCancel {
            get {
                return ResourceManager.GetString("RateThisAppCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Yes!.
        /// </summary>
        internal static string RateThisAppOK {
            get {
                return ResourceManager.GetString("RateThisAppOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Did you like Zombusters? Please help rating this app in the marketplace. Thank you!.
        /// </summary>
        internal static string RateThisAppText {
            get {
                return ResourceManager.GetString("RateThisAppText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rate this App.
        /// </summary>
        internal static string RateThisAppTitle {
            get {
                return ResourceManager.GetString("RateThisAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a READY.
        /// </summary>
        internal static string ReadySelPlayerString {
            get {
                return ResourceManager.GetString("ReadySelPlayerString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please Reconnect Controller.
        /// </summary>
        internal static string ReconnectControllerString {
            get {
                return ResourceManager.GetString("ReconnectControllerString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restart Level.
        /// </summary>
        internal static string RestartLevelInGameString {
            get {
                return ResourceManager.GetString("RestartLevelInGameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Resume Game.
        /// </summary>
        internal static string ResumeGame {
            get {
                return ResourceManager.GetString("ResumeGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Quit game and return to Xbox Dashboard..
        /// </summary>
        internal static string ReturnToDashboardMMString {
            get {
                return ResourceManager.GetString("ReturnToDashboardMMString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a QUIT TO XBOX DASHBOARD.
        /// </summary>
        internal static string ReturnToDashboardString {
            get {
                return ResourceManager.GetString("ReturnToDashboardString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Return to Lobby.
        /// </summary>
        internal static string ReturnToLobby {
            get {
                return ResourceManager.GetString("ReturnToLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a REVIEW APP.
        /// </summary>
        internal static string ReviewMenuString {
            get {
                return ResourceManager.GetString("ReviewMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please help us and review Zombusters! Thanks!.
        /// </summary>
        internal static string ReviewMMString {
            get {
                return ResourceManager.GetString("ReviewMMString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save and Exit.
        /// </summary>
        internal static string SaveAndExitString {
            get {
                return ResourceManager.GetString("SaveAndExitString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select.
        /// </summary>
        internal static string SelectString {
            get {
                return ResourceManager.GetString("SelectString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a SETTINGS.
        /// </summary>
        internal static string SettingsMenuString {
            get {
                return ResourceManager.GetString("SettingsMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show Gamer Card.
        /// </summary>
        internal static string ShowGamerCardMenuString {
            get {
                return ResourceManager.GetString("ShowGamerCardMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Single Player.
        /// </summary>
        internal static string SinglePlayer {
            get {
                return ResourceManager.GetString("SinglePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sound Effect Volume.
        /// </summary>
        internal static string SoundEffectVolumeString {
            get {
                return ResourceManager.GetString("SoundEffectVolumeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start Game.
        /// </summary>
        internal static string StartGameMenuString {
            get {
                return ResourceManager.GetString("StartGameMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a START MATCHMAKING.
        /// </summary>
        internal static string StartMatchmakingMenuString {
            get {
                return ResourceManager.GetString("StartMatchmakingMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Starts Matchmaking..
        /// </summary>
        internal static string StartMatchmakingMMString {
            get {
                return ResourceManager.GetString("StartMatchmakingMMString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MARKETPLACE.
        /// </summary>
        internal static string StoreMenuString {
            get {
                return ResourceManager.GetString("StoreMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Check out our merchandise on our Official Store at Redbubble.
        /// </summary>
        internal static string StoreMMString {
            get {
                return ResourceManager.GetString("StoreMMString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a even though not all players are ready?.
        /// </summary>
        internal static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Would you like to purchase this game?.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a in order to access this functionality.
        /// </summary>
        internal static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a accessing the network.
        /// </summary>
        internal static string String3 {
            get {
                return ResourceManager.GetString("String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a off or not connected.
        /// </summary>
        internal static string String4 {
            get {
                return ResourceManager.GetString("String4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a or there may be no network connectivity.
        /// </summary>
        internal static string String5 {
            get {
                return ResourceManager.GetString("String5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a between the local machine and session host.
        /// </summary>
        internal static string String6 {
            get {
                return ResourceManager.GetString("String6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a the lobby before you can join this session.
        /// </summary>
        internal static string String7 {
            get {
                return ResourceManager.GetString("String7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a A button, Space, Enter = ok.
        /// </summary>
        internal static string String8 {
            get {
                return ResourceManager.GetString("String8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a B button, Esc = cancel.
        /// </summary>
        internal static string String9 {
            get {
                return ResourceManager.GetString("String9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Switch Ready.
        /// </summary>
        internal static string SwitchReadyMenuString {
            get {
                return ResourceManager.GetString("SwitchReadyMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a System Link.
        /// </summary>
        internal static string SystemLink {
            get {
                return ResourceManager.GetString("SystemLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Toggle Ready.
        /// </summary>
        internal static string ToggleReadyMenuString {
            get {
                return ResourceManager.GetString("ToggleReadyMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Trial Mode.
        /// </summary>
        internal static string TrialModeMenuString {
            get {
                return ResourceManager.GetString("TrialModeMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unlock Full Game.
        /// </summary>
        internal static string UnlockFullGameMenuString {
            get {
                return ResourceManager.GetString("UnlockFullGameMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a For more info and news!.
        /// </summary>
        internal static string VisitRetrowaxMenuStringWP {
            get {
                return ResourceManager.GetString("VisitRetrowaxMenuStringWP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Waiting for players....
        /// </summary>
        internal static string WaitingForPlayersMenuString {
            get {
                return ResourceManager.GetString("WaitingForPlayersMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a WAVE.
        /// </summary>
        internal static string WaveGameplayString {
            get {
                return ResourceManager.GetString("WaveGameplayString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ADD ZOMBUSTERS TO MY WISHLIST.
        /// </summary>
        internal static string WishListGameMenu {
            get {
                return ResourceManager.GetString("WishListGameMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a If you want to support us we would appreciate if you add Zombusters to your wishlist..
        /// </summary>
        internal static string WishListGameMenuHelp {
            get {
                return ResourceManager.GetString("WishListGameMenuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a PLAY.
        /// </summary>
        internal static string WPPlayNewGame {
            get {
                return ResourceManager.GetString("WPPlayNewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start a new game..
        /// </summary>
        internal static string WPPlayNewGameMMString {
            get {
                return ResourceManager.GetString("WPPlayNewGameMMString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shake your device to change the song currently played.
        /// </summary>
        internal static string WPShakeToChangeSong {
            get {
                return ResourceManager.GetString("WPShakeToChangeSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tap screen to start.
        /// </summary>
        internal static string WPTapScreen {
            get {
                return ResourceManager.GetString("WPTapScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tip:.
        /// </summary>
        internal static string WPTip {
            get {
                return ResourceManager.GetString("WPTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You saved the city! You are the new city Hero!.
        /// </summary>
        internal static string YouSavedCityEndGameString {
            get {
                return ResourceManager.GetString("YouSavedCityEndGameString", resourceCulture);
            }
        }
    }
}
