//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZombustersWindows.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZombustersWindows.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHALLENGES.
        /// </summary>
        internal static string AchievementsMenuString {
            get {
                return ResourceManager.GetString("AchievementsMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show challenges list..
        /// </summary>
        internal static string AchievementsMMString {
            get {
                return ResourceManager.GetString("AchievementsMMString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zombusters uses an Autosave feature wich will automatically 
        ///save your progress throughout the title. Autosave will 
        ///overwrite information without confirmation. Do not switch 
        ///off the power when the autosave indication is present..
        /// </summary>
        internal static string AutosaveStartMenuString {
            get {
                return ResourceManager.GetString("AutosaveStartMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTOSAVE.
        /// </summary>
        internal static string AutosaveTitleMenuString {
            get {
                return ResourceManager.GetString("AutosaveTitleMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string BackString {
            get {
                return ResourceManager.GetString("BackString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Without Saving.
        /// </summary>
        internal static string BackWithoutSavingString {
            get {
                return ResourceManager.GetString("BackWithoutSavingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelString {
            get {
                return ResourceManager.GetString("CancelString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Character.
        /// </summary>
        internal static string ChangeCharacterMenuString {
            get {
                return ResourceManager.GetString("ChangeCharacterMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Sound/Music Volume.
        /// </summary>
        internal static string ChangeSoundVolumeMenuString {
            get {
                return ResourceManager.GetString("ChangeSoundVolumeMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT CHARACTER.
        /// </summary>
        internal static string CharacterSelectString {
            get {
                return ResourceManager.GetString("CharacterSelectString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLEARED.
        /// </summary>
        internal static string ClearedGameplayString {
            get {
                return ResourceManager.GetString("ClearedGameplayString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string ConfigurationString {
            get {
                return ResourceManager.GetString("ConfigurationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to end this session?.
        /// </summary>
        internal static string ConfirmEndSession {
            get {
                return ResourceManager.GetString("ConfirmEndSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit this sample?.
        /// </summary>
        internal static string ConfirmExitSample {
            get {
                return ResourceManager.GetString("ConfirmExitSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to start the game,.
        /// </summary>
        internal static string ConfirmForceStartGame {
            get {
                return ResourceManager.GetString("ConfirmForceStartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to leave this session?.
        /// </summary>
        internal static string ConfirmLeaveSession {
            get {
                return ResourceManager.GetString("ConfirmLeaveSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online gameplay is not available in trial mode..
        /// </summary>
        internal static string ConfirmMarketplace {
            get {
                return ResourceManager.GetString("ConfirmMarketplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to quit this game?.
        /// </summary>
        internal static string ConfirmQuitGame {
            get {
                return ResourceManager.GetString("ConfirmQuitGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will return to matchmaking menu.
        /// </summary>
        internal static string ConfirmReturnMainMenuMMString {
            get {
                return ResourceManager.GetString("ConfirmReturnMainMenuMMString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit?.
        /// </summary>
        internal static string ConfirmReturnMainMenuString {
            get {
                return ResourceManager.GetString("ConfirmReturnMainMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONGRATULATIONS!.
        /// </summary>
        internal static string CongratssEndGameString {
            get {
                return ResourceManager.GetString("CongratssEndGameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect controller to play.
        /// </summary>
        internal static string ConnectControllerToJoinString {
            get {
                return ResourceManager.GetString("ConnectControllerToJoinString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © RETROWAX GAMES. 2011-2013 ALL RIGHTS RESERVED.
        /// </summary>
        internal static string CopyRightString {
            get {
                return ResourceManager.GetString("CopyRightString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE GAME.
        /// </summary>
        internal static string CreateGameMenuString {
            get {
                return ResourceManager.GetString("CreateGameMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host a game..
        /// </summary>
        internal static string CreateGameMMString {
            get {
                return ResourceManager.GetString("CreateGameMMString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Session.
        /// </summary>
        internal static string CreateSession {
            get {
                return ResourceManager.GetString("CreateSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREDITS.
        /// </summary>
        internal static string CreditsMenuString {
            get {
                return ResourceManager.GetString("CreditsMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show creator credits..
        /// </summary>
        internal static string CreditsMMString {
            get {
                return ResourceManager.GetString("CreditsMMString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THANKS FOR PLAYING!.
        /// </summary>
        internal static string CreditsThanksForPlayingString {
            get {
                return ResourceManager.GetString("CreditsThanksForPlayingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CUSTOM MATCH.
        /// </summary>
        internal static string CustomMatchMenuString {
            get {
                return ResourceManager.GetString("CustomMatchMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search for a game session to join within a set of 
        ///parameters..
        /// </summary>
        internal static string CustomMatchMMString {
            get {
                return ResourceManager.GetString("CustomMatchMMString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Session.
        /// </summary>
        internal static string EndSession {
            get {
                return ResourceManager.GetString("EndSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost connection to the network session.
        /// </summary>
        internal static string ErrorDisconnected {
            get {
                return ResourceManager.GetString("ErrorDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must sign in a suitable gamer profile.
        /// </summary>
        internal static string ErrorGamerPrivilege {
            get {
                return ResourceManager.GetString("ErrorGamerPrivilege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host ended the session.
        /// </summary>
        internal static string ErrorHostEndedSession {
            get {
                return ResourceManager.GetString("ErrorHostEndedSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while.
        /// </summary>
        internal static string ErrorNetwork {
            get {
                return ResourceManager.GetString("ErrorNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Networking is turned.
        /// </summary>
        internal static string ErrorNetworkNotAvailable {
            get {
                return ResourceManager.GetString("ErrorNetworkNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host kicked you out of the session.
        /// </summary>
        internal static string ErrorRemovedByHost {
            get {
                return ResourceManager.GetString("ErrorRemovedByHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This session is already full.
        /// </summary>
        internal static string ErrorSessionFull {
            get {
                return ResourceManager.GetString("ErrorSessionFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session not found. It may have ended,.
        /// </summary>
        internal static string ErrorSessionNotFound {
            get {
                return ResourceManager.GetString("ErrorSessionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must wait for the host to return to.
        /// </summary>
        internal static string ErrorSessionNotJoinable {
            get {
                return ResourceManager.GetString("ErrorSessionNotJoinable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This functionality is not available in trial mode.
        /// </summary>
        internal static string ErrorTrialMode {
            get {
                return ResourceManager.GetString("ErrorTrialMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred.
        /// </summary>
        internal static string ErrorUnknown {
            get {
                return ResourceManager.GetString("ErrorUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXTRAS.
        /// </summary>
        internal static string ExtrasMenuString {
            get {
                return ResourceManager.GetString("ExtrasMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the Extras menu. You can check how to play,
        ///Scoreboards or Credits..
        /// </summary>
        internal static string ExtrasMMString {
            get {
                return ResourceManager.GetString("ExtrasMMString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIND SESSION.
        /// </summary>
        internal static string FindSessionMenuString {
            get {
                return ResourceManager.GetString("FindSessionMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find session to play..
        /// </summary>
        internal static string FindSessionMMString {
            get {
                return ResourceManager.GetString("FindSessionMMString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Sessions.
        /// </summary>
        internal static string FindSessions {
            get {
                return ResourceManager.GetString("FindSessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This party is open to friends..
        /// </summary>
        internal static string FriendOpenGroupString {
            get {
                return ResourceManager.GetString("FriendOpenGroupString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle full screen mode.
        /// </summary>
        internal static string FullScreenMenuString {
            get {
                return ResourceManager.GetString("FullScreenMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GAME OVER.
        /// </summary>
        internal static string GameOverString {
            get {
                return ResourceManager.GetString("GameOverString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart from current wave.
        /// </summary>
        internal static string GPRestartCurrentWaveString {
            get {
                return ResourceManager.GetString("GPRestartCurrentWaveString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart from beginning.
        /// </summary>
        internal static string GPRestartFromBeginningString {
            get {
                return ResourceManager.GetString("GPRestartFromBeginningString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to return to the party lobby. Any unsaved progress will be lost..
        /// </summary>
        internal static string GPReturnLobbySupportString {
            get {
                return ResourceManager.GetString("GPReturnLobbySupportString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to return to the main menu. The session will disband, and any unsaved progress will be lost..
        /// </summary>
        internal static string GPReturnMMSupportString {
            get {
                return ResourceManager.GetString("GPReturnMMSupportString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to Main Menu.
        /// </summary>
        internal static string GPReturnToMainMenuString {
            get {
                return ResourceManager.GetString("GPReturnToMainMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  (host).
        /// </summary>
        internal static string HostSuffix {
            get {
                return ResourceManager.GetString("HostSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to Play.
        /// </summary>
        internal static string HowToPlayInGameString {
            get {
                return ResourceManager.GetString("HowToPlayInGameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIM + SHOOT.
        /// </summary>
        internal static string HTPAimShootString {
            get {
                return ResourceManager.GetString("HTPAimShootString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGE SONG.
        /// </summary>
        internal static string HTPChangeSongString {
            get {
                return ResourceManager.GetString("HTPChangeSongString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGE WEAPON.
        /// </summary>
        internal static string HTPChangeWeaponString {
            get {
                return ResourceManager.GetString("HTPChangeWeaponString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the Left Thumbstick to move your character.
        ///Use the Right Thumbsitck to fire at the Zombies.
        ///Shoot the enemies to accumulate points and to get
        ///PowerUps. Catch the PowerUps to gain a free life 
        ///or a new Weapon..
        /// </summary>
        internal static string HTPExplanationString {
            get {
                return ResourceManager.GetString("HTPExplanationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GRENADE.
        /// </summary>
        internal static string HTPGrenadeString {
            get {
                return ResourceManager.GetString("HTPGrenadeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How to play Zombusters..
        /// </summary>
        internal static string HTPMenuSupportString {
            get {
                return ResourceManager.GetString("HTPMenuSupportString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOVE.
        /// </summary>
        internal static string HTPMoveString {
            get {
                return ResourceManager.GetString("HTPMoveString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAUSE GAME.
        /// </summary>
        internal static string HTPPauseString {
            get {
                return ResourceManager.GetString("HTPPauseString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REVIVE TEAMMATE.
        /// </summary>
        internal static string HTPReviveTeammateString {
            get {
                return ResourceManager.GetString("HTPReviveTeammateString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TAUNT.
        /// </summary>
        internal static string HTPTauntString {
            get {
                return ResourceManager.GetString("HTPTauntString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite.
        /// </summary>
        internal static string InviteMenuString {
            get {
                return ResourceManager.GetString("InviteMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Session.
        /// </summary>
        internal static string JoinSession {
            get {
                return ResourceManager.GetString("JoinSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leaderboards.
        /// </summary>
        internal static string LeaderboardMenuString {
            get {
                return ResourceManager.GetString("LeaderboardMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check out the score of your friends online or Local.
        /// </summary>
        internal static string LeaderboardMMString {
            get {
                return ResourceManager.GetString("LeaderboardMMString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SCORE.
        /// </summary>
        internal static string LeaderboardScoreString {
            get {
                return ResourceManager.GetString("LeaderboardScoreString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave.
        /// </summary>
        internal static string LeaveMenuString {
            get {
                return ResourceManager.GetString("LeaveMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Session.
        /// </summary>
        internal static string LeaveSession {
            get {
                return ResourceManager.GetString("LeaveSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEVEL SELECTION.
        /// </summary>
        internal static string LevelSelectionString {
            get {
                return ResourceManager.GetString("LevelSelectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEVEL.
        /// </summary>
        internal static string LevelSelectMenuString {
            get {
                return ResourceManager.GetString("LevelSelectMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the level to play..
        /// </summary>
        internal static string LevelSelectMMString {
            get {
                return ResourceManager.GetString("LevelSelectMMString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lobby.
        /// </summary>
        internal static string Lobby {
            get {
                return ResourceManager.GetString("Lobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOBBY.
        /// </summary>
        internal static string LobbyMenuString {
            get {
                return ResourceManager.GetString("LobbyMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start a local game. You can play with three more
        ///players on the same console..
        /// </summary>
        internal static string LocalGameMMString {
            get {
                return ResourceManager.GetString("LocalGameMMString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOCAL GAME.
        /// </summary>
        internal static string LocalGameString {
            get {
                return ResourceManager.GetString("LocalGameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Menu.
        /// </summary>
        internal static string MainMenu {
            get {
                return ResourceManager.GetString("MainMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Main Menu Lobby.
        /// </summary>
        internal static string MainMenuLobbyString {
            get {
                return ResourceManager.GetString("MainMenuLobbyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAIN MENU.
        /// </summary>
        internal static string MainMenuString {
            get {
                return ResourceManager.GetString("MainMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to host a new game?.
        /// </summary>
        internal static string MatchmakingHostOwnGameString {
            get {
                return ResourceManager.GetString("MatchmakingHostOwnGameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Matchmaking Lobby.
        /// </summary>
        internal static string MatchmakingLobbyString {
            get {
                return ResourceManager.GetString("MatchmakingLobbyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MATCHMAKING.
        /// </summary>
        internal static string MatchmakingMenuString {
            get {
                return ResourceManager.GetString("MatchmakingMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take your party to Xbox LIVE and into the frenetic 
        ///action of live combat. Up to four players co-operate 
        ///to survive wave after wave of the Zombie horde..
        /// </summary>
        internal static string MatchmakingMMString {
            get {
                return ResourceManager.GetString("MatchmakingMMString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAX. PLAYERS.
        /// </summary>
        internal static string MaxPlayersMenuString {
            get {
                return ResourceManager.GetString("MaxPlayersMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many players would you like to play?.
        /// </summary>
        internal static string MaxPlayersMMString {
            get {
                return ResourceManager.GetString("MaxPlayersMMString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string MessageBoxUsage {
            get {
                return ResourceManager.GetString("MessageBoxUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} joined.
        /// </summary>
        internal static string MessageGamerJoined {
            get {
                return ResourceManager.GetString("MessageGamerJoined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} left.
        /// </summary>
        internal static string MessageGamerLeft {
            get {
                return ResourceManager.GetString("MessageGamerLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music Volume.
        /// </summary>
        internal static string MusicVolumeString {
            get {
                return ResourceManager.GetString("MusicVolumeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY PARTY.
        /// </summary>
        internal static string MyGroupString {
            get {
                return ResourceManager.GetString("MyGroupString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Networking....
        /// </summary>
        internal static string NetworkBusy {
            get {
                return ResourceManager.GetString("NetworkBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose your Network for the Matchmaking. Play a 
        ///SystemLink or Xbox Live game..
        /// </summary>
        internal static string NetworkMatchmakingMMString {
            get {
                return ResourceManager.GetString("NetworkMatchmakingMMString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NETWORK.
        /// </summary>
        internal static string NetworkMatchmakingString {
            get {
                return ResourceManager.GetString("NetworkMatchmakingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No sessions found.
        /// </summary>
        internal static string NoSessionsFound {
            get {
                return ResourceManager.GetString("NoSessionsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eight.
        /// </summary>
        internal static string NumberEight {
            get {
                return ResourceManager.GetString("NumberEight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Five.
        /// </summary>
        internal static string NumberFive {
            get {
                return ResourceManager.GetString("NumberFive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Four.
        /// </summary>
        internal static string NumberFour {
            get {
                return ResourceManager.GetString("NumberFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nine.
        /// </summary>
        internal static string NumberNine {
            get {
                return ResourceManager.GetString("NumberNine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One.
        /// </summary>
        internal static string NumberOne {
            get {
                return ResourceManager.GetString("NumberOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seven.
        /// </summary>
        internal static string NumberSeven {
            get {
                return ResourceManager.GetString("NumberSeven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Six.
        /// </summary>
        internal static string NumberSix {
            get {
                return ResourceManager.GetString("NumberSix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ten.
        /// </summary>
        internal static string NumberTen {
            get {
                return ResourceManager.GetString("NumberTen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three.
        /// </summary>
        internal static string NumberThree {
            get {
                return ResourceManager.GetString("NumberThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two.
        /// </summary>
        internal static string NumberTwo {
            get {
                return ResourceManager.GetString("NumberTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player 1 Press Start.
        /// </summary>
        internal static string P1PressStartString {
            get {
                return ResourceManager.GetString("P1PressStartString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player 2 Press Start.
        /// </summary>
        internal static string P2PressStartString {
            get {
                return ResourceManager.GetString("P2PressStartString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player 3 Press Start.
        /// </summary>
        internal static string P3PressStartString {
            get {
                return ResourceManager.GetString("P3PressStartString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player 4 Press Start.
        /// </summary>
        internal static string P4PressStartString {
            get {
                return ResourceManager.GetString("P4PressStartString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite Party.
        /// </summary>
        internal static string PartyMenuString {
            get {
                return ResourceManager.GetString("PartyMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        internal static string Paused {
            get {
                return ResourceManager.GetString("Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use A,S,D,W or Arrows to move your character.
        ///Use Left Mouse Button to fire at the Zombies.
        ///Shoot the enemies to accumulate points and to get
        ///PowerUps. Catch the PowerUps to gain a free life 
        ///or a new Weapon..
        /// </summary>
        internal static string PCExplanationString {
            get {
                return ResourceManager.GetString("PCExplanationString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press Any Key.
        /// </summary>
        internal static string PCPressAnyKeyString {
            get {
                return ResourceManager.GetString("PCPressAnyKeyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Four.
        /// </summary>
        internal static string PlayerFourString {
            get {
                return ResourceManager.GetString("PlayerFourString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIVE.
        /// </summary>
        internal static string PlayerMatch {
            get {
                return ResourceManager.GetString("PlayerMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player One.
        /// </summary>
        internal static string PlayerOneString {
            get {
                return ResourceManager.GetString("PlayerOneString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press GUIDE to Sign In.
        /// </summary>
        internal static string PlayerSignInString {
            get {
                return ResourceManager.GetString("PlayerSignInString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Three.
        /// </summary>
        internal static string PlayerThreeString {
            get {
                return ResourceManager.GetString("PlayerThreeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player Two.
        /// </summary>
        internal static string PlayerTwoString {
            get {
                return ResourceManager.GetString("PlayerTwoString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts playlist for the selected Machmaking configuration..
        /// </summary>
        internal static string PlaylistMatchmakingMMString {
            get {
                return ResourceManager.GetString("PlaylistMatchmakingMMString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLAYLIST.
        /// </summary>
        internal static string PlaylistMatchmakingString {
            get {
                return ResourceManager.GetString("PlaylistMatchmakingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepare for the next Wave.
        /// </summary>
        internal static string PrepareNextWaveGameplayString {
            get {
                return ResourceManager.GetString("PrepareNextWaveGameplayString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press START button.
        /// </summary>
        internal static string PressStartString {
            get {
                return ResourceManager.GetString("PressStartString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRIVATE SLOTS.
        /// </summary>
        internal static string PrivateSlotsMenuString {
            get {
                return ResourceManager.GetString("PrivateSlotsMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select number of private slots..
        /// </summary>
        internal static string PrivateSlotsMMString {
            get {
                return ResourceManager.GetString("PrivateSlotsMMString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUICK MATCH.
        /// </summary>
        internal static string QuickMatchMenuString {
            get {
                return ResourceManager.GetString("QuickMatchMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quickly join another player&apos;s game session..
        /// </summary>
        internal static string QuickMatchMMString {
            get {
                return ResourceManager.GetString("QuickMatchMMString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit Game.
        /// </summary>
        internal static string QuitGame {
            get {
                return ResourceManager.GetString("QuitGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit to Main Menu.
        /// </summary>
        internal static string QuitToMainMenuInGameString {
            get {
                return ResourceManager.GetString("QuitToMainMenuInGameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Later.
        /// </summary>
        internal static string RateThisAppCancel {
            get {
                return ResourceManager.GetString("RateThisAppCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes!.
        /// </summary>
        internal static string RateThisAppOK {
            get {
                return ResourceManager.GetString("RateThisAppOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did you like Zombusters? Please help rating this app in the marketplace. Thank you!.
        /// </summary>
        internal static string RateThisAppText {
            get {
                return ResourceManager.GetString("RateThisAppText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate this App.
        /// </summary>
        internal static string RateThisAppTitle {
            get {
                return ResourceManager.GetString("RateThisAppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to READY.
        /// </summary>
        internal static string ReadySelPlayerString {
            get {
                return ResourceManager.GetString("ReadySelPlayerString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Reconnect Controller.
        /// </summary>
        internal static string ReconnectControllerString {
            get {
                return ResourceManager.GetString("ReconnectControllerString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Level.
        /// </summary>
        internal static string RestartLevelInGameString {
            get {
                return ResourceManager.GetString("RestartLevelInGameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume Game.
        /// </summary>
        internal static string ResumeGame {
            get {
                return ResourceManager.GetString("ResumeGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quit game and return to Xbox Dashboard..
        /// </summary>
        internal static string ReturnToDashboardMMString {
            get {
                return ResourceManager.GetString("ReturnToDashboardMMString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUIT TO XBOX DASHBOARD.
        /// </summary>
        internal static string ReturnToDashboardString {
            get {
                return ResourceManager.GetString("ReturnToDashboardString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to Lobby.
        /// </summary>
        internal static string ReturnToLobby {
            get {
                return ResourceManager.GetString("ReturnToLobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REVIEW APP.
        /// </summary>
        internal static string ReviewMenuString {
            get {
                return ResourceManager.GetString("ReviewMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please help us and review Zombusters! Thanks!.
        /// </summary>
        internal static string ReviewMMString {
            get {
                return ResourceManager.GetString("ReviewMMString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and Exit.
        /// </summary>
        internal static string SaveAndExitString {
            get {
                return ResourceManager.GetString("SaveAndExitString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string SelectString {
            get {
                return ResourceManager.GetString("SelectString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS.
        /// </summary>
        internal static string SettingsMenuString {
            get {
                return ResourceManager.GetString("SettingsMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Gamer Card.
        /// </summary>
        internal static string ShowGamerCardMenuString {
            get {
                return ResourceManager.GetString("ShowGamerCardMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Player.
        /// </summary>
        internal static string SinglePlayer {
            get {
                return ResourceManager.GetString("SinglePlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound Effect Volume.
        /// </summary>
        internal static string SoundEffectVolumeString {
            get {
                return ResourceManager.GetString("SoundEffectVolumeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Game.
        /// </summary>
        internal static string StartGameMenuString {
            get {
                return ResourceManager.GetString("StartGameMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START MATCHMAKING.
        /// </summary>
        internal static string StartMatchmakingMenuString {
            get {
                return ResourceManager.GetString("StartMatchmakingMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts Matchmaking..
        /// </summary>
        internal static string StartMatchmakingMMString {
            get {
                return ResourceManager.GetString("StartMatchmakingMMString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to even though not all players are ready?.
        /// </summary>
        internal static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to purchase this game?.
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in order to access this functionality.
        /// </summary>
        internal static string String2 {
            get {
                return ResourceManager.GetString("String2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to accessing the network.
        /// </summary>
        internal static string String3 {
            get {
                return ResourceManager.GetString("String3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to off or not connected.
        /// </summary>
        internal static string String4 {
            get {
                return ResourceManager.GetString("String4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or there may be no network connectivity.
        /// </summary>
        internal static string String5 {
            get {
                return ResourceManager.GetString("String5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to between the local machine and session host.
        /// </summary>
        internal static string String6 {
            get {
                return ResourceManager.GetString("String6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the lobby before you can join this session.
        /// </summary>
        internal static string String7 {
            get {
                return ResourceManager.GetString("String7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A button, Space, Enter = ok.
        /// </summary>
        internal static string String8 {
            get {
                return ResourceManager.GetString("String8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B button, Esc = cancel.
        /// </summary>
        internal static string String9 {
            get {
                return ResourceManager.GetString("String9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch Ready.
        /// </summary>
        internal static string SwitchReadyMenuString {
            get {
                return ResourceManager.GetString("SwitchReadyMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Link.
        /// </summary>
        internal static string SystemLink {
            get {
                return ResourceManager.GetString("SystemLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle Ready.
        /// </summary>
        internal static string ToggleReadyMenuString {
            get {
                return ResourceManager.GetString("ToggleReadyMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial Mode.
        /// </summary>
        internal static string TrialModeMenuString {
            get {
                return ResourceManager.GetString("TrialModeMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock Full Game.
        /// </summary>
        internal static string UnlockFullGameMenuString {
            get {
                return ResourceManager.GetString("UnlockFullGameMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For more info and news!.
        /// </summary>
        internal static string VisitRetrowaxMenuStringWP {
            get {
                return ResourceManager.GetString("VisitRetrowaxMenuStringWP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for players....
        /// </summary>
        internal static string WaitingForPlayersMenuString {
            get {
                return ResourceManager.GetString("WaitingForPlayersMenuString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WAVE.
        /// </summary>
        internal static string WaveGameplayString {
            get {
                return ResourceManager.GetString("WaveGameplayString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string WPPlayNewGame {
            get {
                return ResourceManager.GetString("WPPlayNewGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start a new game..
        /// </summary>
        internal static string WPPlayNewGameMMString {
            get {
                return ResourceManager.GetString("WPPlayNewGameMMString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shake your device to change the song currently played.
        /// </summary>
        internal static string WPShakeToChangeSong {
            get {
                return ResourceManager.GetString("WPShakeToChangeSong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tap screen to start.
        /// </summary>
        internal static string WPTapScreen {
            get {
                return ResourceManager.GetString("WPTapScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip:.
        /// </summary>
        internal static string WPTip {
            get {
                return ResourceManager.GetString("WPTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You saved the city! You are the new city Hero!.
        /// </summary>
        internal static string YouSavedCityEndGameString {
            get {
                return ResourceManager.GetString("YouSavedCityEndGameString", resourceCulture);
            }
        }
    }
}
