//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZombustersWindows.Localization
{
    using System;
    using System.Reflection;


    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings()
        {
        }

        /// <summary>
        ///   Devuelve la instancia de ResourceLoader almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZombustersWindows.Localization.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        internal static global::Windows.ApplicationModel.Resources.ResourceLoader ResourceLoader
        {
            get
            {
                var resourceLoader = Windows.ApplicationModel.Resources.ResourceLoader.GetForCurrentView();
                return resourceLoader;
            }
        }

        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a CHALLENGES.
        /// </summary>
        internal static string AchievementsMenuString
        {
            get
            {
                return ResourceLoader.GetString("AchievementsMenuString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Show challenges list..
        /// </summary>
        internal static string AchievementsMMString
        {
            get
            {
                return ResourceLoader.GetString("AchievementsMMString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Zombusters uses an Autosave feature wich will automatically 
        ///save your progress throughout the title. Autosave will 
        ///overwrite information without confirmation. Do not switch 
        ///off the power when the autosave indication is present..
        /// </summary>
        internal static string AutosaveStartMenuString
        {
            get
            {
                return ResourceLoader.GetString("AutosaveStartMenuString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a AUTOSAVE.
        /// </summary>
        internal static string AutosaveTitleMenuString
        {
            get
            {
                return ResourceLoader.GetString("AutosaveTitleMenuString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Back.
        /// </summary>
        internal static string BackString
        {
            get
            {
                return ResourceLoader.GetString("BackString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Exit Without Saving.
        /// </summary>
        internal static string BackWithoutSavingString
        {
            get
            {
                return ResourceLoader.GetString("BackWithoutSavingString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        internal static string CancelString
        {
            get
            {
                return ResourceLoader.GetString("CancelString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Change Character.
        /// </summary>
        internal static string ChangeCharacterMenuString
        {
            get
            {
                return ResourceLoader.GetString("ChangeCharacterMenuString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Change Language.
        /// </summary>
        internal static string ChangeLanguageOption
        {
            get
            {
                return ResourceLoader.GetString("ChangeLanguageOption");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Change Sound/Music Volume.
        /// </summary>
        internal static string ChangeSoundVolumeMenuString
        {
            get
            {
                return ResourceLoader.GetString("ChangeSoundVolumeMenuString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a SELECT CHARACTER.
        /// </summary>
        internal static string CharacterSelectString
        {
            get
            {
                return ResourceLoader.GetString("CharacterSelectString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a CLEARED.
        /// </summary>
        internal static string ClearedGameplayString
        {
            get
            {
                return ResourceLoader.GetString("ClearedGameplayString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Settings.
        /// </summary>
        internal static string ConfigurationString
        {
            get
            {
                return ResourceLoader.GetString("ConfigurationString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to end this session?.
        /// </summary>
        internal static string ConfirmEndSession
        {
            get
            {
                return ResourceLoader.GetString("ConfirmEndSession");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to exit this sample?.
        /// </summary>
        internal static string ConfirmExitSample
        {
            get
            {
                return ResourceLoader.GetString("ConfirmExitSample");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to start the game,.
        /// </summary>
        internal static string ConfirmForceStartGame
        {
            get
            {
                return ResourceLoader.GetString("ConfirmForceStartGame");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to leave this session?.
        /// </summary>
        internal static string ConfirmLeaveSession
        {
            get
            {
                return ResourceLoader.GetString("ConfirmLeaveSession");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Online gameplay is not available in trial mode..
        /// </summary>
        internal static string ConfirmMarketplace
        {
            get
            {
                return ResourceLoader.GetString("ConfirmMarketplace");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to quit this game?.
        /// </summary>
        internal static string ConfirmQuitGame
        {
            get
            {
                return ResourceLoader.GetString("ConfirmQuitGame");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a You will return to matchmaking menu.
        /// </summary>
        internal static string ConfirmReturnMainMenuMMString
        {
            get
            {
                return ResourceLoader.GetString("ConfirmReturnMainMenuMMString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to exit?.
        /// </summary>
        internal static string ConfirmReturnMainMenuString
        {
            get
            {
                return ResourceLoader.GetString("ConfirmReturnMainMenuString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a CONGRATULATIONS!.
        /// </summary>
        internal static string CongratssEndGameString
        {
            get
            {
                return ResourceLoader.GetString("CongratssEndGameString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Connect controller to play.
        /// </summary>
        internal static string ConnectControllerToJoinString
        {
            get
            {
                return ResourceLoader.GetString("ConnectControllerToJoinString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a © RETROWAX GAMES. 2011-2020 ALL RIGHTS RESERVED.
        /// </summary>
        internal static string CopyRightString
        {
            get
            {
                return ResourceLoader.GetString("CopyRightString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a CREATE GAME.
        /// </summary>
        internal static string CreateGameMenuString
        {
            get
            {
                return ResourceLoader.GetString("CreateGameMenuString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Host a game..
        /// </summary>
        internal static string CreateGameMMString
        {
            get
            {
                return ResourceLoader.GetString("CreateGameMMString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Create Session.
        /// </summary>
        internal static string CreateSession
        {
            get
            {
                return ResourceLoader.GetString("CreateSession");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a CREDITS.
        /// </summary>
        internal static string CreditsMenuString
        {
            get
            {
                return ResourceLoader.GetString("CreditsMenuString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Show creator credits..
        /// </summary>
        internal static string CreditsMMString
        {
            get
            {
                return ResourceLoader.GetString("CreditsMMString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a THANKS FOR PLAYING!.
        /// </summary>
        internal static string CreditsThanksForPlayingString
        {
            get
            {
                return ResourceLoader.GetString("CreditsThanksForPlayingString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a CUSTOM MATCH.
        /// </summary>
        internal static string CustomMatchMenuString
        {
            get
            {
                return ResourceLoader.GetString("CustomMatchMenuString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Search for a game session to join within a set of 
        ///parameters..
        /// </summary>
        internal static string CustomMatchMMString
        {
            get
            {
                return ResourceLoader.GetString("CustomMatchMMString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a We hope you have enjoyed the Demo.
        /// </summary>
        internal static string DemoEndScreenLine1
        {
            get
            {
                return ResourceLoader.GetString("DemoEndScreenLine1");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Prepare for more kind of enemies, more weapons, more power-ups and more surprises!.
        /// </summary>
        internal static string DemoEndScreenLine2
        {
            get
            {
                return ResourceLoader.GetString("DemoEndScreenLine2");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Be sure to stop by the Steam page and add the game to your Wishlist.
        /// </summary>
        internal static string DemoEndScreenLine3
        {
            get
            {
                return ResourceLoader.GetString("DemoEndScreenLine3");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Zombusters will be released fall 2020.
        /// </summary>
        internal static string DemoEndScreenLine4
        {
            get
            {
                return ResourceLoader.GetString("DemoEndScreenLine4");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a End Session.
        /// </summary>
        internal static string EndSession
        {
            get
            {
                return ResourceLoader.GetString("EndSession");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Lost connection to the network session.
        /// </summary>
        internal static string ErrorDisconnected
        {
            get
            {
                return ResourceLoader.GetString("ErrorDisconnected");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a You must sign in a suitable gamer profile.
        /// </summary>
        internal static string ErrorGamerPrivilege
        {
            get
            {
                return ResourceLoader.GetString("ErrorGamerPrivilege");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Host ended the session.
        /// </summary>
        internal static string ErrorHostEndedSession
        {
            get
            {
                return ResourceLoader.GetString("ErrorHostEndedSession");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a There was an error while.
        /// </summary>
        internal static string ErrorNetwork
        {
            get
            {
                return ResourceLoader.GetString("ErrorNetwork");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Networking is turned.
        /// </summary>
        internal static string ErrorNetworkNotAvailable
        {
            get
            {
                return ResourceLoader.GetString("ErrorNetworkNotAvailable");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Host kicked you out of the session.
        /// </summary>
        internal static string ErrorRemovedByHost
        {
            get
            {
                return ResourceLoader.GetString("ErrorRemovedByHost");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a This session is already full.
        /// </summary>
        internal static string ErrorSessionFull
        {
            get
            {
                return ResourceLoader.GetString("ErrorSessionFull");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Session not found. It may have ended,.
        /// </summary>
        internal static string ErrorSessionNotFound
        {
            get
            {
                return ResourceLoader.GetString("ErrorSessionNotFound");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a You must wait for the host to return to.
        /// </summary>
        internal static string ErrorSessionNotJoinable
        {
            get
            {
                return ResourceLoader.GetString("ErrorSessionNotJoinable");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a This functionality is not available in trial mode.
        /// </summary>
        internal static string ErrorTrialMode
        {
            get
            {
                return ResourceLoader.GetString("ErrorTrialMode");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a An unknown error occurred.
        /// </summary>
        internal static string ErrorUnknown
        {
            get
            {
                return ResourceLoader.GetString("ErrorUnknown");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Exit.
        /// </summary>
        internal static string Exit
        {
            get
            {
                return ResourceLoader.GetString("Exit");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a EXTRAS.
        /// </summary>
        internal static string ExtrasMenuString
        {
            get
            {
                return ResourceLoader.GetString("ExtrasMenuString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Show the Extras menu. You can check how to play,
        ///Scoreboards or Credits..
        /// </summary>
        internal static string ExtrasMMString
        {
            get
            {
                return ResourceLoader.GetString("ExtrasMMString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a FIND SESSION.
        /// </summary>
        internal static string FindSessionMenuString
        {
            get
            {
                return ResourceLoader.GetString("FindSessionMenuString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Find session to play..
        /// </summary>
        internal static string FindSessionMMString
        {
            get
            {
                return ResourceLoader.GetString("FindSessionMMString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Find Sessions.
        /// </summary>
        internal static string FindSessions
        {
            get
            {
                return ResourceLoader.GetString("FindSessions");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a This party is open to friends..
        /// </summary>
        internal static string FriendOpenGroupString
        {
            get
            {
                return ResourceLoader.GetString("FriendOpenGroupString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Toggle full screen mode.
        /// </summary>
        internal static string FullScreenMenuString
        {
            get
            {
                return ResourceLoader.GetString("FullScreenMenuString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a GAME OVER.
        /// </summary>
        internal static string GameOverString
        {
            get
            {
                return ResourceLoader.GetString("GameOverString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Restart from current wave.
        /// </summary>
        internal static string GPRestartCurrentWaveString
        {
            get
            {
                return ResourceLoader.GetString("GPRestartCurrentWaveString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Restart from beginning.
        /// </summary>
        internal static string GPRestartFromBeginningString
        {
            get
            {
                return ResourceLoader.GetString("GPRestartFromBeginningString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a You are about to return to the party lobby. Any unsaved progress will be lost..
        /// </summary>
        internal static string GPReturnLobbySupportString
        {
            get
            {
                return ResourceLoader.GetString("GPReturnLobbySupportString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a You are about to return to the main menu. The session will disband, and any unsaved progress will be lost..
        /// </summary>
        internal static string GPReturnMMSupportString
        {
            get
            {
                return ResourceLoader.GetString("GPReturnMMSupportString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Return to Main Menu.
        /// </summary>
        internal static string GPReturnToMainMenuString
        {
            get
            {
                return ResourceLoader.GetString("GPReturnToMainMenuString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a  (host).
        /// </summary>
        internal static string HostSuffix
        {
            get
            {
                return ResourceLoader.GetString("HostSuffix");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a HOW TO PLAY.
        /// </summary>
        internal static string HowToPlayInGameString
        {
            get
            {
                return ResourceLoader.GetString("HowToPlayInGameString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a AIM + SHOOT.
        /// </summary>
        internal static string HTPAimShootString
        {
            get
            {
                return ResourceLoader.GetString("HTPAimShootString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a CHANGE SONG.
        /// </summary>
        internal static string HTPChangeSongString
        {
            get
            {
                return ResourceLoader.GetString("HTPChangeSongString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a CHANGE WEAPON.
        /// </summary>
        internal static string HTPChangeWeaponString
        {
            get
            {
                return ResourceLoader.GetString("HTPChangeWeaponString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Use the Left Thumbstick to move your character.
        ///Use the Right Thumbsitck to fire at the Zombies.
        ///Shoot the enemies to accumulate points and to get
        ///PowerUps. Catch the PowerUps to gain a free life 
        ///or a new Weapon..
        /// </summary>
        internal static string HTPExplanationString
        {
            get
            {
                return ResourceLoader.GetString("HTPExplanationString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a GRENADE.
        /// </summary>
        internal static string HTPGrenadeString
        {
            get
            {
                return ResourceLoader.GetString("HTPGrenadeString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a How to play Zombusters..
        /// </summary>
        internal static string HTPMenuSupportString
        {
            get
            {
                return ResourceLoader.GetString("HTPMenuSupportString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a MOVE.
        /// </summary>
        internal static string HTPMoveString
        {
            get
            {
                return ResourceLoader.GetString("HTPMoveString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a PAUSE GAME.
        /// </summary>
        internal static string HTPPauseString
        {
            get
            {
                return ResourceLoader.GetString("HTPPauseString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a REVIVE TEAMMATE.
        /// </summary>
        internal static string HTPReviveTeammateString
        {
            get
            {
                return ResourceLoader.GetString("HTPReviveTeammateString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a TAUNT.
        /// </summary>
        internal static string HTPTauntString
        {
            get
            {
                return ResourceLoader.GetString("HTPTauntString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Invite.
        /// </summary>
        internal static string InviteMenuString
        {
            get
            {
                return ResourceLoader.GetString("InviteMenuString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Join Session.
        /// </summary>
        internal static string JoinSession
        {
            get
            {
                return ResourceLoader.GetString("JoinSession");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a LEADERBOARDS.
        /// </summary>
        internal static string LeaderboardMenuString
        {
            get
            {
                return ResourceLoader.GetString("LeaderboardMenuString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Check out the score of your friends online or Local.
        /// </summary>
        internal static string LeaderboardMMString
        {
            get
            {
                return ResourceLoader.GetString("LeaderboardMMString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a SCORE.
        /// </summary>
        internal static string LeaderboardScoreString
        {
            get
            {
                return ResourceLoader.GetString("LeaderboardScoreString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Leave.
        /// </summary>
        internal static string LeaveMenuString
        {
            get
            {
                return ResourceLoader.GetString("LeaveMenuString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Leave Session.
        /// </summary>
        internal static string LeaveSession
        {
            get
            {
                return ResourceLoader.GetString("LeaveSession");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a LEVEL SELECTION.
        /// </summary>
        internal static string LevelSelectionString
        {
            get
            {
                return ResourceLoader.GetString("LevelSelectionString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a LEVEL.
        /// </summary>
        internal static string LevelSelectMenuString
        {
            get
            {
                return ResourceLoader.GetString("LevelSelectMenuString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Choose the level to play..
        /// </summary>
        internal static string LevelSelectMMString
        {
            get
            {
                return ResourceLoader.GetString("LevelSelectMMString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Loading....
        /// </summary>
        internal static string Loading
        {
            get
            {
                return ResourceLoader.GetString("Loading");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Lobby.
        /// </summary>
        internal static string Lobby
        {
            get
            {
                return ResourceLoader.GetString("Lobby");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a LOBBY.
        /// </summary>
        internal static string LobbyMenuString
        {
            get
            {
                return ResourceLoader.GetString("LobbyMenuString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Start a local game. You can play with three more
        ///players on the same console..
        /// </summary>
        internal static string LocalGameMMString
        {
            get
            {
                return ResourceLoader.GetString("LocalGameMMString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a LOCAL GAME.
        /// </summary>
        internal static string LocalGameString
        {
            get
            {
                return ResourceLoader.GetString("LocalGameString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Main Menu.
        /// </summary>
        internal static string MainMenu
        {
            get
            {
                return ResourceLoader.GetString("MainMenu");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a In Main Menu Lobby.
        /// </summary>
        internal static string MainMenuLobbyString
        {
            get
            {
                return ResourceLoader.GetString("MainMenuLobbyString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a MAIN MENU.
        /// </summary>
        internal static string MainMenuString
        {
            get
            {
                return ResourceLoader.GetString("MainMenuString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Would you like to host a new game?.
        /// </summary>
        internal static string MatchmakingHostOwnGameString
        {
            get
            {
                return ResourceLoader.GetString("MatchmakingHostOwnGameString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a In Matchmaking Lobby.
        /// </summary>
        internal static string MatchmakingLobbyString
        {
            get
            {
                return ResourceLoader.GetString("MatchmakingLobbyString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a MATCHMAKING.
        /// </summary>
        internal static string MatchmakingMenuString
        {
            get
            {
                return ResourceLoader.GetString("MatchmakingMenuString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Take your party to Xbox LIVE and into the frenetic 
        ///action of live combat. Up to four players co-operate 
        ///to survive wave after wave of the Zombie horde..
        /// </summary>
        internal static string MatchmakingMMString
        {
            get
            {
                return ResourceLoader.GetString("MatchmakingMMString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a MAX. PLAYERS.
        /// </summary>
        internal static string MaxPlayersMenuString
        {
            get
            {
                return ResourceLoader.GetString("MaxPlayersMenuString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a How many players would you like to play?.
        /// </summary>
        internal static string MaxPlayersMMString
        {
            get
            {
                return ResourceLoader.GetString("MaxPlayersMMString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a .
        /// </summary>
        internal static string MessageBoxUsage
        {
            get
            {
                return ResourceLoader.GetString("MessageBoxUsage");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a {0} joined.
        /// </summary>
        internal static string MessageGamerJoined
        {
            get
            {
                return ResourceLoader.GetString("MessageGamerJoined");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a {0} left.
        /// </summary>
        internal static string MessageGamerLeft
        {
            get
            {
                return ResourceLoader.GetString("MessageGamerLeft");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Music Volume.
        /// </summary>
        internal static string MusicVolumeString
        {
            get
            {
                return ResourceLoader.GetString("MusicVolumeString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a MY PARTY.
        /// </summary>
        internal static string MyGroupString
        {
            get
            {
                return ResourceLoader.GetString("MyGroupString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Networking....
        /// </summary>
        internal static string NetworkBusy
        {
            get
            {
                return ResourceLoader.GetString("NetworkBusy");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Choose your Network for the Matchmaking. Play a 
        ///SystemLink or Xbox Live game..
        /// </summary>
        internal static string NetworkMatchmakingMMString
        {
            get
            {
                return ResourceLoader.GetString("NetworkMatchmakingMMString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a NETWORK.
        /// </summary>
        internal static string NetworkMatchmakingString
        {
            get
            {
                return ResourceLoader.GetString("NetworkMatchmakingString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a No sessions found.
        /// </summary>
        internal static string NoSessionsFound
        {
            get
            {
                return ResourceLoader.GetString("NoSessionsFound");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Eight.
        /// </summary>
        internal static string NumberEight
        {
            get
            {
                return ResourceLoader.GetString("NumberEight");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Five.
        /// </summary>
        internal static string NumberFive
        {
            get
            {
                return ResourceLoader.GetString("NumberFive");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Four.
        /// </summary>
        internal static string NumberFour
        {
            get
            {
                return ResourceLoader.GetString("NumberFour");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Nine.
        /// </summary>
        internal static string NumberNine
        {
            get
            {
                return ResourceLoader.GetString("NumberNine");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a One.
        /// </summary>
        internal static string NumberOne
        {
            get
            {
                return ResourceLoader.GetString("NumberOne");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Seven.
        /// </summary>
        internal static string NumberSeven
        {
            get
            {
                return ResourceLoader.GetString("NumberSeven");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Six.
        /// </summary>
        internal static string NumberSix
        {
            get
            {
                return ResourceLoader.GetString("NumberSix");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Ten.
        /// </summary>
        internal static string NumberTen
        {
            get
            {
                return ResourceLoader.GetString("NumberTen");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Three.
        /// </summary>
        internal static string NumberThree
        {
            get
            {
                return ResourceLoader.GetString("NumberThree");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Two.
        /// </summary>
        internal static string NumberTwo
        {
            get
            {
                return ResourceLoader.GetString("NumberTwo");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Player 1 Press Start.
        /// </summary>
        internal static string P1PressStartString
        {
            get
            {
                return ResourceLoader.GetString("P1PressStartString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Player 2 Press Start.
        /// </summary>
        internal static string P2PressStartString
        {
            get
            {
                return ResourceLoader.GetString("P2PressStartString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Player 3 Press Start.
        /// </summary>
        internal static string P3PressStartString
        {
            get
            {
                return ResourceLoader.GetString("P3PressStartString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Player 4 Press Start.
        /// </summary>
        internal static string P4PressStartString
        {
            get
            {
                return ResourceLoader.GetString("P4PressStartString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Invite Party.
        /// </summary>
        internal static string PartyMenuString
        {
            get
            {
                return ResourceLoader.GetString("PartyMenuString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Paused.
        /// </summary>
        internal static string Paused
        {
            get
            {
                return ResourceLoader.GetString("Paused");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Use A,S,D,W or Arrows to move your character.
        ///Use Left Mouse Button to fire at the Zombies.
        ///Shoot the enemies to accumulate points and to get
        ///PowerUps. Catch the PowerUps to gain a free life 
        ///or a new Weapon..
        /// </summary>
        internal static string PCExplanationString
        {
            get
            {
                return ResourceLoader.GetString("PCExplanationString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Press Any Key.
        /// </summary>
        internal static string PCPressAnyKeyString
        {
            get
            {
                return ResourceLoader.GetString("PCPressAnyKeyString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Player Four.
        /// </summary>
        internal static string PlayerFourString
        {
            get
            {
                return ResourceLoader.GetString("PlayerFourString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a LIVE.
        /// </summary>
        internal static string PlayerMatch
        {
            get
            {
                return ResourceLoader.GetString("PlayerMatch");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Player One.
        /// </summary>
        internal static string PlayerOneString
        {
            get
            {
                return ResourceLoader.GetString("PlayerOneString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Press GUIDE to Sign In.
        /// </summary>
        internal static string PlayerSignInString
        {
            get
            {
                return ResourceLoader.GetString("PlayerSignInString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Player Three.
        /// </summary>
        internal static string PlayerThreeString
        {
            get
            {
                return ResourceLoader.GetString("PlayerThreeString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Player Two.
        /// </summary>
        internal static string PlayerTwoString
        {
            get
            {
                return ResourceLoader.GetString("PlayerTwoString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Starts playlist for the selected Machmaking configuration..
        /// </summary>
        internal static string PlaylistMatchmakingMMString
        {
            get
            {
                return ResourceLoader.GetString("PlaylistMatchmakingMMString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a PLAYLIST.
        /// </summary>
        internal static string PlaylistMatchmakingString
        {
            get
            {
                return ResourceLoader.GetString("PlaylistMatchmakingString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Prepare for the next Wave.
        /// </summary>
        internal static string PrepareNextWaveGameplayString
        {
            get
            {
                return ResourceLoader.GetString("PrepareNextWaveGameplayString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Press START button.
        /// </summary>
        internal static string PressStartString
        {
            get
            {
                return ResourceLoader.GetString("PressStartString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a PRIVATE SLOTS.
        /// </summary>
        internal static string PrivateSlotsMenuString
        {
            get
            {
                return ResourceLoader.GetString("PrivateSlotsMenuString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Select number of private slots..
        /// </summary>
        internal static string PrivateSlotsMMString
        {
            get
            {
                return ResourceLoader.GetString("PrivateSlotsMMString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a QUICK MATCH.
        /// </summary>
        internal static string QuickMatchMenuString
        {
            get
            {
                return ResourceLoader.GetString("QuickMatchMenuString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Quickly join another player&apos;s game session..
        /// </summary>
        internal static string QuickMatchMMString
        {
            get
            {
                return ResourceLoader.GetString("QuickMatchMMString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a QUIT GAME.
        /// </summary>
        internal static string QuitGame
        {
            get
            {
                return ResourceLoader.GetString("QuitGame");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Quit to Main Menu.
        /// </summary>
        internal static string QuitToMainMenuInGameString
        {
            get
            {
                return ResourceLoader.GetString("QuitToMainMenuInGameString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Later.
        /// </summary>
        internal static string RateThisAppCancel
        {
            get
            {
                return ResourceLoader.GetString("RateThisAppCancel");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Yes!.
        /// </summary>
        internal static string RateThisAppOK
        {
            get
            {
                return ResourceLoader.GetString("RateThisAppOK");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Did you like Zombusters? Please help rating this app in the marketplace. Thank you!.
        /// </summary>
        internal static string RateThisAppText
        {
            get
            {
                return ResourceLoader.GetString("RateThisAppText");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Rate this App.
        /// </summary>
        internal static string RateThisAppTitle
        {
            get
            {
                return ResourceLoader.GetString("RateThisAppTitle");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a READY.
        /// </summary>
        internal static string ReadySelPlayerString
        {
            get
            {
                return ResourceLoader.GetString("ReadySelPlayerString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Please Reconnect Controller.
        /// </summary>
        internal static string ReconnectControllerString
        {
            get
            {
                return ResourceLoader.GetString("ReconnectControllerString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Restart Level.
        /// </summary>
        internal static string RestartLevelInGameString
        {
            get
            {
                return ResourceLoader.GetString("RestartLevelInGameString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Resume Game.
        /// </summary>
        internal static string ResumeGame
        {
            get
            {
                return ResourceLoader.GetString("ResumeGame");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Quit game and return to Xbox Dashboard..
        /// </summary>
        internal static string ReturnToDashboardMMString
        {
            get
            {
                return ResourceLoader.GetString("ReturnToDashboardMMString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a QUIT TO XBOX DASHBOARD.
        /// </summary>
        internal static string ReturnToDashboardString
        {
            get
            {
                return ResourceLoader.GetString("ReturnToDashboardString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Return to Lobby.
        /// </summary>
        internal static string ReturnToLobby
        {
            get
            {
                return ResourceLoader.GetString("ReturnToLobby");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a REVIEW APP.
        /// </summary>
        internal static string ReviewMenuString
        {
            get
            {
                return ResourceLoader.GetString("ReviewMenuString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Please help us and review Zombusters! Thanks!.
        /// </summary>
        internal static string ReviewMMString
        {
            get
            {
                return ResourceLoader.GetString("ReviewMMString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Save and Exit.
        /// </summary>
        internal static string SaveAndExitString
        {
            get
            {
                return ResourceLoader.GetString("SaveAndExitString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Select.
        /// </summary>
        internal static string SelectString
        {
            get
            {
                return ResourceLoader.GetString("SelectString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a SETTINGS.
        /// </summary>
        internal static string SettingsMenuString
        {
            get
            {
                return ResourceLoader.GetString("SettingsMenuString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Show Gamer Card.
        /// </summary>
        internal static string ShowGamerCardMenuString
        {
            get
            {
                return ResourceLoader.GetString("ShowGamerCardMenuString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Single Player.
        /// </summary>
        internal static string SinglePlayer
        {
            get
            {
                return ResourceLoader.GetString("SinglePlayer");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Sound Effect Volume.
        /// </summary>
        internal static string SoundEffectVolumeString
        {
            get
            {
                return ResourceLoader.GetString("SoundEffectVolumeString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Start Game.
        /// </summary>
        internal static string StartGameMenuString
        {
            get
            {
                return ResourceLoader.GetString("StartGameMenuString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a START MATCHMAKING.
        /// </summary>
        internal static string StartMatchmakingMenuString
        {
            get
            {
                return ResourceLoader.GetString("StartMatchmakingMenuString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Starts Matchmaking..
        /// </summary>
        internal static string StartMatchmakingMMString
        {
            get
            {
                return ResourceLoader.GetString("StartMatchmakingMMString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a MARKETPLACE.
        /// </summary>
        internal static string StoreMenuString
        {
            get
            {
                return ResourceLoader.GetString("StoreMenuString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Check out our merchandise on our Official Store at Redbubble.
        /// </summary>
        internal static string StoreMMString
        {
            get
            {
                return ResourceLoader.GetString("StoreMMString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a even though not all players are ready?.
        /// </summary>
        internal static string String
        {
            get
            {
                return ResourceLoader.GetString("String");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Would you like to purchase this game?.
        /// </summary>
        internal static string String1
        {
            get
            {
                return ResourceLoader.GetString("String1");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a in order to access this functionality.
        /// </summary>
        internal static string String2
        {
            get
            {
                return ResourceLoader.GetString("String2");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a accessing the network.
        /// </summary>
        internal static string String3
        {
            get
            {
                return ResourceLoader.GetString("String3");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a off or not connected.
        /// </summary>
        internal static string String4
        {
            get
            {
                return ResourceLoader.GetString("String4");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a or there may be no network connectivity.
        /// </summary>
        internal static string String5
        {
            get
            {
                return ResourceLoader.GetString("String5");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a between the local machine and session host.
        /// </summary>
        internal static string String6
        {
            get
            {
                return ResourceLoader.GetString("String6");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a the lobby before you can join this session.
        /// </summary>
        internal static string String7
        {
            get
            {
                return ResourceLoader.GetString("String7");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a A button, Space, Enter = ok.
        /// </summary>
        internal static string String8
        {
            get
            {
                return ResourceLoader.GetString("String8");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a B button, Esc = cancel.
        /// </summary>
        internal static string String9
        {
            get
            {
                return ResourceLoader.GetString("String9");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Switch Ready.
        /// </summary>
        internal static string SwitchReadyMenuString
        {
            get
            {
                return ResourceLoader.GetString("SwitchReadyMenuString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a System Link.
        /// </summary>
        internal static string SystemLink
        {
            get
            {
                return ResourceLoader.GetString("SystemLink");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Toggle Ready.
        /// </summary>
        internal static string ToggleReadyMenuString
        {
            get
            {
                return ResourceLoader.GetString("ToggleReadyMenuString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Trial Mode.
        /// </summary>
        internal static string TrialModeMenuString
        {
            get
            {
                return ResourceLoader.GetString("TrialModeMenuString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Unlock Full Game.
        /// </summary>
        internal static string UnlockFullGameMenuString
        {
            get
            {
                return ResourceLoader.GetString("UnlockFullGameMenuString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a For more info and news!.
        /// </summary>
        internal static string VisitRetrowaxMenuStringWP
        {
            get
            {
                return ResourceLoader.GetString("VisitRetrowaxMenuStringWP");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Waiting for players....
        /// </summary>
        internal static string WaitingForPlayersMenuString
        {
            get
            {
                return ResourceLoader.GetString("WaitingForPlayersMenuString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a WAVE.
        /// </summary>
        internal static string WaveGameplayString
        {
            get
            {
                return ResourceLoader.GetString("WaveGameplayString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a ADD ZOMBUSTERS TO MY WISHLIST.
        /// </summary>
        internal static string WishListGameMenu
        {
            get
            {
                return ResourceLoader.GetString("WishListGameMenu");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a If you want to support us we would appreciate if you add Zombusters to your wishlist..
        /// </summary>
        internal static string WishListGameMenuHelp
        {
            get
            {
                return ResourceLoader.GetString("WishListGameMenuHelp");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a PLAY.
        /// </summary>
        internal static string WPPlayNewGame
        {
            get
            {
                return ResourceLoader.GetString("WPPlayNewGame");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Start a new game..
        /// </summary>
        internal static string WPPlayNewGameMMString
        {
            get
            {
                return ResourceLoader.GetString("WPPlayNewGameMMString");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Shake your device to change the song currently played.
        /// </summary>
        internal static string WPShakeToChangeSong
        {
            get
            {
                return ResourceLoader.GetString("WPShakeToChangeSong");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Tap screen to start.
        /// </summary>
        internal static string WPTapScreen
        {
            get
            {
                return ResourceLoader.GetString("WPTapScreen");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a Tip:.
        /// </summary>
        internal static string WPTip
        {
            get
            {
                return ResourceLoader.GetString("WPTip");
            }
        }

        /// <summary>
        ///   Busca una cadena traducida similar a You saved the city! You are the new city Hero!.
        /// </summary>
        internal static string YouSavedCityEndGameString
        {
            get
            {
                return ResourceLoader.GetString("YouSavedCityEndGameString");
            }
        }
    }
}
